### ISSUE TITLE
Using thread_pool_executors causes segfault

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1112]
Using the thread_pool_executor class causes a segmentation fault if it is used with more than one core.

**Comment by sithhell** [comment]
The test covering this issue is still occasionally segfaulting. See for example here:
http://hermione.cct.lsu.edu/builders/hpx_gcc_4_7_boost_1_51_debian_x86_64_debug/builds/295/steps/run_regression_tests/logs/stdio

From a quick look at the failure, it looks like the segfault is cause when trying to execute one of the registered shutdown functions. I don't know why this happens.

**Comment by hkaiser** [comment]
This has been fixed by 48565b98c8f51658f2a0f2faf0376ddedb5fca5e
