### ISSUE TITLE
Better document CMake usage

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1258]
Some things need better documentation:
- [ ] generated make targets.
- [ ] some cmake variables

**Comment by msimberg** [comment]
- Would documenting the use of `make help` be enough for the first point?
- Are there any particular undocumented/badly documented cmake variables that you're thinking of? Otherwise I can volunteer to at least look for variables which don't have any documentation.

**Comment by sithhell** [comment]
Yeah, what I had in mind was a more thorough guide through the various
options describing their implications in more detail. A few example use
cases would help as well, for example how to enable the different
sanitizers. Common CMAKE_CXX_FLAGS options to enable various other helpful
things (for example -march=native or -pg) etc.

**Comment by msimberg** [comment]
@tapaswenipathak this issue is quite open-ended and subjective. In my opinion the first point (generated CMake targets) is fairly well described [here](https://stellar-group.github.io/hpx/docs/sphinx/branches/master/html/manual/building_hpx.html#basic-information). I think the second concerns two things: HPX-defined CMake variables and CMake-defined variables. The first is documented fairly well [here](https://stellar-group.github.io/hpx/docs/sphinx/branches/master/html/manual/building_hpx.html#cmake-variables-used-to-configure-hpx), but it's quite a long list and the descriptions are not very detailed. In particular it's hard to know as a user which ones are actually important. I can't really say how to concretely improve that without spending some extra time on it (which I'm not sure I have now). The second part is CMake-defined variables, which I'm not convinced we should document too much, simply because these things are most likely described better elsewhere. I think @sithhell's idea is to document "best practices" for profiling, debugging, etc. A bit in the style of https://stellar-group.github.io/hpx/docs/sphinx/branches/master/html/manual/debugging_hpx_applications.html#using-sanitizers-with-hpx-applications. These will never be comprehensive because things work differently on different OS's.

**Comment by tapaswenipathak** [comment]
Ack @msimberg.

**Comment by msimberg** [comment]
We should maybe keep this open... One problem with the current way of documenting CMake options is that they are not all picked up in the docs build since some are never even defined depending on the values of other options. We could either have all options defined independently of other options but, or we could just document the options separately from the CMake files (but this would require enforcing that documentation is actually written).

**Comment by hkaiser** [comment]
I'm fine with re-opening this. For the documentation of options: I think ensuring that we automate things as much as possible should be a major criteria for decisions.
