### ISSUE TITLE
Configure setting HPX_HAVE_PARCELPORT_MPI is ignored

### ISSUE THREAD

**Issue by eschnett** [STEllAR-GROUP/hpx#1429]
I want to configure HPX 0.9.10 with MPI on a Linux system. I am using this cmake invokation:
```bash
  cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_C_COMPILER="$CC" \
  -DCMAKE_CXX_COMPILER="$CXX" \
  -DCMAKE_Fortran_COMPILER="$FC" \
  -DCMAKE_C_FLAGS="$BOOST_CFLAGS $HDF5_CFLAGS $HWLOC_CFLAGS $JEMALLOC_CFLAGS" \
  -DCMAKE_CXX_FLAGS="$CXX11FLAGS $BOOST_CXXFLAGS $HDF5_CXXFLAGS $HWLOC_CXXFLAGS $JEMALLOC_CXXFLAGS $PAPI_CXXFLAGS $QTHREADS_CXXFLAGS" \
  -DCMAKE_Fortran_FLAGS="" \
  -DCMAKE_EXE_LINKER_FLAGS="$CXX11FLAGS $BOOST_CXXFLAGS $HDF5_CXXFLAGS $HWLOC_CXXFLAGS $JEMALLOC_CXXFLAGS $PAPI_CXXFLAGS $BOOST_LDFLAGS $HDF5_LDFLAGS $HWLOC_LDFLAGS $JEMALLOC_LDFLAGS $PAPI_LDFLAGS $QTHREADS_LDFLAGS" \
  -DHPX_HAVE_PARCELPORT_MPI=ON \
  -DMPI_C_COMPILER="$MPICC" \
  -DMPI_CXX_COMPILER="$MPICXX" \
  -DMPI_Fortran_COMPILER="$MPIFC" \
  -DMPI_C_COMPILE_FLAGS="$MPI_CFLAGS" \
  -DMPI_CXX_COMPILE_FLAGS="$MPI_CXXFLAGS" \
  -DMPI_Fortran_COMPILE_FLAGS="$MPI_FFLAGS" \
  -DMPI_C_INCLUDE_PATH="$OPENMPI_DIR/include" \
  -DMPI_CXX_INCLUDE_PATH="$OPENMPI_DIR/include" \
  -DMPI_Fortran_INCLUDE_PATH="$OPENMPI_DIR/include" \
  -DMPI_C_LINK_FLAGS="$MPI_LDFLAGS" \
  -DMPI_CXX_LINK_FLAGS="$MPI_LDFLAGS" \
  -DMPI_Fortran_LINK_FLAGS="$MPI_LDFLAGS" \
  -DMPI_C_LIBRARIES="$MPI_LIBS" \
  -DMPI_CXX_LIBRARIES="$MPI_LIBS" \
  -DMPI_Fortran_LIBRARIES="$MPI_LIBS" \
  -DHPX_MALLOC=jemalloc \
  -DHPX_CMAKE_LOGLEVEL=Debug \
  -DBOOST_ROOT="$BOOST_DIR" \
  -DHDF5_ROOT="$HDF5_DIR" \
  -DHWLOC_ROOT="$HWLOC_DIR" \
  -DJEMALLOC_ROOT="$JEMALLOC_DIR" \
  -DPAPI_ROOT="$PAPI_DIR" \
  -DQTHREADS_ROOT="$QTHREADS_DIR" \
  -DCMAKE_INSTALL_PREFIX=/home/eschnett/software/hpx-0.9.10 \
  /home/eschnett/software/src/hpx-0.9.10
```

The configure stage ends with outputting these lines:
```
    HDF5_ROOT
    HPX_HAVE_PARCELPORT_MPI
    MPI_CXX_COMPILER
    MPI_CXX_COMPILE_FLAGS
    MPI_CXX_INCLUDE_PATH
    MPI_CXX_LIBRARIES
    MPI_CXX_LINK_FLAGS
    MPI_C_COMPILER
    MPI_C_COMPILE_FLAGS
    MPI_C_INCLUDE_PATH
    MPI_C_LIBRARIES
    MPI_C_LINK_FLAGS
    MPI_Fortran_COMPILER
    MPI_Fortran_COMPILE_FLAGS
    MPI_Fortran_INCLUDE_PATH
    MPI_Fortran_LIBRARIES
    MPI_Fortran_LINK_FLAGS
    PAPI_ROOT
```

The complete screen output is available at <https://gist.github.com/eschnett/e8e1c88e57db07ab33ce>.

I have the feeling that this HPX installation does not support MPI. When I start an HPX application via `mpirun -np 2`, it runs twice independently. When I call it with the option
```bash
./hello_hpx --hpx:ini=hpx.parcel.mpi.enable=1
```
then I receive the error message
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<hpx::exception> >'
  what():  Attempt to initialize unknown entry:  <command line definitions>: line 1 (offending entry: hpx.parcel.mpi.enable=1): HPX(no_success)
```

How do I configure HPX so that it enables the MPI parcelport? Note that the cmake option `-DHPX_HAVE_PARCELPORT_MPI=ON` is already present.

**Comment by pagrubel** [comment]
did you try
mpirun hello_hpx

On Mar 28, 2015, at 7:01 PM, Erik Schnetter <notifications@github.com<mailto:notifications@github.com>> wrote:


I want to configure HPX 0.9.10 with MPI on a Linux system. I am using this cmake invokation:

  cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_C_COMPILER="$CC" \
  -DCMAKE_CXX_COMPILER="$CXX" \
  -DCMAKE_Fortran_COMPILER="$FC" \
  -DCMAKE_C_FLAGS="$BOOST_CFLAGS $HDF5_CFLAGS $HWLOC_CFLAGS $JEMALLOC_CFLAGS" \
  -DCMAKE_CXX_FLAGS="$CXX11FLAGS $BOOST_CXXFLAGS $HDF5_CXXFLAGS $HWLOC_CXXFLAGS $JEMALLOC_CXXFLAGS $PAPI_CXXFLAGS $QTHREADS_CXXFLAGS" \
  -DCMAKE_Fortran_FLAGS="" \
  -DCMAKE_EXE_LINKER_FLAGS="$CXX11FLAGS $BOOST_CXXFLAGS $HDF5_CXXFLAGS $HWLOC_CXXFLAGS $JEMALLOC_CXXFLAGS $PAPI_CXXFLAGS $BOOST_LDFLAGS $HDF5_LDFLAGS $HWLOC_LDFLAGS $JEMALLOC_LDFLAGS $PAPI_LDFLAGS $QTHREADS_LDFLAGS" \
  -DHPX_HAVE_PARCELPORT_MPI=ON \
  -DMPI_C_COMPILER="$MPICC" \
  -DMPI_CXX_COMPILER="$MPICXX" \
  -DMPI_Fortran_COMPILER="$MPIFC" \
  -DMPI_C_COMPILE_FLAGS="$MPI_CFLAGS" \
  -DMPI_CXX_COMPILE_FLAGS="$MPI_CXXFLAGS" \
  -DMPI_Fortran_COMPILE_FLAGS="$MPI_FFLAGS" \
  -DMPI_C_INCLUDE_PATH="$OPENMPI_DIR/include" \
  -DMPI_CXX_INCLUDE_PATH="$OPENMPI_DIR/include" \
  -DMPI_Fortran_INCLUDE_PATH="$OPENMPI_DIR/include" \
  -DMPI_C_LINK_FLAGS="$MPI_LDFLAGS" \
  -DMPI_CXX_LINK_FLAGS="$MPI_LDFLAGS" \
  -DMPI_Fortran_LINK_FLAGS="$MPI_LDFLAGS" \
  -DMPI_C_LIBRARIES="$MPI_LIBS" \
  -DMPI_CXX_LIBRARIES="$MPI_LIBS" \
  -DMPI_Fortran_LIBRARIES="$MPI_LIBS" \
  -DHPX_MALLOC=jemalloc \
  -DHPX_CMAKE_LOGLEVEL=Debug \
  -DBOOST_ROOT="$BOOST_DIR" \
  -DHDF5_ROOT="$HDF5_DIR" \
  -DHWLOC_ROOT="$HWLOC_DIR" \
  -DJEMALLOC_ROOT="$JEMALLOC_DIR" \
  -DPAPI_ROOT="$PAPI_DIR" \
  -DQTHREADS_ROOT="$QTHREADS_DIR" \
  -DCMAKE_INSTALL_PREFIX=/home/eschnett/software/hpx-0.9.10 \
  /home/eschnett/software/src/hpx-0.9.10

The configure stage ends with outputting these lines:

    HDF5_ROOT
    HPX_HAVE_PARCELPORT_MPI
    MPI_CXX_COMPILER
    MPI_CXX_COMPILE_FLAGS
    MPI_CXX_INCLUDE_PATH
    MPI_CXX_LIBRARIES
    MPI_CXX_LINK_FLAGS
    MPI_C_COMPILER
    MPI_C_COMPILE_FLAGS
    MPI_C_INCLUDE_PATH
    MPI_C_LIBRARIES
    MPI_C_LINK_FLAGS
    MPI_Fortran_COMPILER
    MPI_Fortran_COMPILE_FLAGS
    MPI_Fortran_INCLUDE_PATH
    MPI_Fortran_LIBRARIES
    MPI_Fortran_LINK_FLAGS
    PAPI_ROOT


The complete screen output is available at https://gist.github.com/eschnett/e8e1c88e57db07ab33ce.

I have the feeling that this HPX installation does not support MPI. When I start an HPX application via mpirun -np 2, it runs twice independently. When I call it with the option

./hello_hpx --hpx:ini=hpx.parcel.mpi.enable=1

then I receive the error message

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<hpx::exception> >'
  what():  Attempt to initialize unknown entry:  <command line definitions>: line 1 (offending entry: hpx.parcel.mpi.enable=1): HPX(no_success)


How do I configure HPX so that it enables the MPI parcelport? Note that the cmake option -DHPX_HAVE_PARCELPORT_MPI=ON is already present.

**Comment by sithhell** [comment]
Please see here:
http://stellar-group.github.io/hpx/docs/html/hpx/manual/build_system/building_hpx/cmake_variables.html#build_system.cmake_variables.HPX_PARCELPORT_MPI

For the correct option to enable the mpi pp.

**Comment by hkaiser** [comment]
@sithhell: The currently used options (`HPX_PARCELPORT_XXX`) are really inconsistent with the `HPX_HAVE_SOMETHING_SOMTHING` options we have otherwise. Should we unify those?

**Comment by eschnett** [comment]
I guess the name of the cmake variable changed at some point in the past? The variable `HPX_HAVE_PARCELPORT_MPI` used to work fine on the master...

Thanks!

**Comment by sithhell** [comment]
Yes indeed, the option was named that way a (ca1d7832bf7669fc714f4dc39d2a0c89790e8643 changed it 8 months ago) that option change was announced on the ML and part of the 0.9.9 release. We currently have three sets of options: `HPX_XXX`, `HPX_HAVE_XXX` and `HPX_WITH_XXX` I am impartial what to use there, but I think those inconsistencies are orthogonal to this particular issue. Please discuss a possible resolution in #1430.
