### ISSUE TITLE
The hpx prefix isn't set correctly when building applications against a installed version of HPX

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1503]
When having HPX applications using `hpx/hpx_main`, the default prefix will resolve to the build directory. This gets problematic when HPX gets installed to `CMAKE_INSTALL_PREFIX` and the automatic deduction of the hpx prefix can not be used due to missing functionality of the underlying operating system (affected are bluegeneq and xeonphi).

**Comment by hkaiser** [comment]
The whole point of doing the dance around `libhpx_init` was to allow for passing the proper `HPX_PREFIX` while building the application. At startup we want to look in two directories for dynamic components by default: `<hpx-install_path>/bin/hpx` (i.e. relative to the installation directory of `libhpx`)and `<application-base-dir>/hpx` (i.e. relative to the directory where the executable is located when run).

Normally we can extract this information at runtime - and we do so [here](https://github.com/STEllAR-GROUP/hpx/blob/master/src/util/find_prefix.cpp#L51) and [here](https://github.com/STEllAR-GROUP/hpx/blob/master/src/util/find_prefix.cpp#L103). 

The first is disabled for Xeon/Phi (and others) as those platforms do not support the required functionality in `libdl`. In those cases the HPX_PREFIX configured at compile time is used as a fallback.

**Comment by quantomb** [comment]
This may be related to a problem that I noticed with the parquet code compilation. If I do a fresh clone from git and try to run a build script which  says:
#!/bin/bash                                                                      
                                                                                 
SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )                                        
INSTALL_PATH=$SCRIPTPATH/install                                                 
BUILD_PATH=$SCRIPTPATH/build                                                     
                                                                                 
if [ "$1" = "clean" ]; then                                                      
    rm -rf $INSTALL_PATH $BUILD_PATH                                             
    exit 0                                                                       
fi                                                                               
                                                                                 
#export CC=$TACC_LLVM_BIN/clang                                                  
#export CXX=$TACC_LLVM_BIN/clang++                                               
                                                                                 
if [ ! -d "$BUILD_PATH" ]; then                                                  
  mkdir -p "$BUILD_PATH"                                                         
                                                                                 
  cd "$BUILD_PATH"                                                               
                                                                                 
  cmake -DCMAKE_BUILD_TYPE=Release                              \                
        -DHPX_WITH_MALLOC="jemalloc"                                 \           
        -DHPX_DIR:PATH=/home/skellar/hpxdir/hpxmain/install/lib/cmake/hpx \           
        -Wdev                                                     \              
         $SCRIPTPATH/workbench                                                   
#/Files/Packages/hpx/install/lib/cmake/hpx   \                                   
#        -DHPX_WITH_THREAD_IDLE_RATES=ON                      \                  
#        -DHPX_DIR:PATH=/home/skellar/hpxdir/hpxcur/install/lib/cmake/hpx \         
fi                                                                               
                                                                                 
cd "$BUILD_PATH"                                                                 
                                                                                 
make $1        

I get the error :

CMake Error at /home/skellar/hpxdir/hpxcur/hpx/cmake/HPX_Message.cmake:43 (message):
  ERROR: The specified allocators do not match.  This Project is configured
  with jemalloc and HPX was configured with tcmalloc.
Call Stack (most recent call first):
  /home/skellar/hpxdir/hpxcur/build/lib/cmake/HPX/HPXMacros.cmake:53 (hpx_error)
  /home/skellar/hpxdir/hpxcur/build/lib/cmake/HPX/HPXConfig.cmake:58 (hpx_setup_allocator)
  CMakeLists.txt:23 (find_package)


Which is odd because it is trying to link with the wrong version of HPX and I can't figure why it is ignoring the path I try to set in my script.

**Comment by msimberg** [comment]
@sithhell @hkaiser Is this still something that will/should be fixed?
