### ISSUE TITLE
HPX code contribution policy needs to be better standardized and documented 

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#1587]
A section needs to be added to the main HPX documentation http://stellar-group.github.io/hpx/docs/html/ outlining the procedures for contributing and extending those mentioned here https://github.com/STEllAR-GROUP/hpx/blob/master/CONTRIBUTING.md. The documentation should address the points raised in the dev list email from @K-ballo reproduced below (with minor corrections and additions) for completeness
- Changes: how to incorporate them into the codebase? should they be
  tested before? how to communicate them to other developers? how to
  communicate them to users? how to keep them from being inadvertently
  reverted in the future? how are breaking changes decided?
- Reviews: should changes be reviewed/which changes should be
  reviewed? should review feedback be addressed? who gets to sign off a
  review? can reviews happen for existing code or already incorporated
  changes? how should those be handled?
- Compiler support: which compilers/platforms/stlibs are supported?
  how is this decided? what are the implications of said choice? how is
  this tested?
- Git: is it just a backup mechanism? should commits be a unit of
  change? should they have a descriptive message, and how should that
  message be formatted? does history matter? are tools like git-blame and
  git-bisect supported by the development model?
- Style: naming, formatting, braces, line length, whitespace, etc? is
  there an official style and why is it the way it is? concerns of
  readability and discoverability (grep)
- Headers and includes: should there be #includes for things that are
  used? should there be #includes for things that are not used? should
  there be guaranteed transitive #includes and which ones? should there be
  forwarding headers? when does forward declarations matter? what about
  monolythic headers? what about "include" headers (headers that just
  # include a bunch of stuff)?
- Tests: what to test for? which changes deserve tests? which fixes
  deserve tests? what to do with a failing test? do test results matter?
- Docs: ... Should large patches be accepted without accompanying 
  documentation?
- C++11/14 features: which C++11/14 features should be required? which
  should be allowed optionally? whatever is supported? how is this
  decided? how are those documented?
- "Patterns": certain patterns naturally arise during development, to
  workaround compiler bugs/limitations, reduce compilation time, reduce
  binary size, for compatibility reasons, for performance reasons.. what
  are these patterns and why are they needed/used? how to make
  contributors aware of them?
- Compilation time: does it matter? when does it stop being a compiler
  problem and start being the code's fault? how to address it?

**Comment by aserio** [comment]
@biddisco Do you think that we should be placing this document in the HPX Documentation? Would anyone be able to comment on where other projects like HPX place these documents?

**Comment by hkaiser** [comment]
The [Python PEP document system](https://www.python.org/dev/peps/) looks like something we could model our process after. There I see a couple of documents which (in slightly adapted form) express many of the things we should formalize. 

@biddisco: My suggestion would be not to add these documents to the immediate HPX documentation but to keep them in a separate spot (Wiki? Dedicated website?). I see the formalization of our development process (including guidelines, overviews, rules, proposals, etc.) as reaching beyond the actual HPX development. Nothing prevents us from linking those from the HPX documentation, though.

**Comment by biddisco** [comment]
@hkaiser @aserio My suggestion to put them in the main HPX docs was mainly because I have them bookmarked and I use them constantly to check command-line options and things like that. I treat it as the first point of contact when I'm looking for info and I didn't see anything about contributing code in there. I didn't realize the contributing document existed until I started actively looking for it and so yes, a reference in the main docs linking to other doc/s would be sufficient.

I looked briefly at the PEP referenced, but it was too much material for me to go through now so I'm not sure what to say.

I am torn because on the one hand I'd like to see development standardized so that the dashboards stay as green as possible, on the other hand, I have stopped contributing to some other projects because they place too many restrictions on code contributions. I am involved in R&D and not developing 'products', so when my code is rejected because I didn't put curly brackets on a new line (which is a waste of space in many cases), then I question the validity of the process - it may seem trivial, but if someone contributes a complex parallel algorithm (or parcelport say) and it is rejected because the indentation is wrong or the variable names use the wrong case - and the developer contributes to N projects, all with different requirements for code style etc, how much time should the developer be expected to spend on making everything 'perfect'.

**Comment by sithhell** [comment]
Am 08.06.2015 9:14 vorm. schrieb "John Biddiscombe" <
notifications@github.com>:
>
> I am torn because on the one hand I'd like to see development
standardized so that the dashboards stay as green as possible, on the other
hand, I have stopped contributing to some other projects because they place
too many restrictions on code contributions. I am involved in R&D and not
developing 'products', so when my code is rejected because I didn't put
curly brackets on a new line (which is a waste of space in many cases),
then I question the validity of the process - it may seem trivial, but if
someone contributes a complex parallel algorithm (or parcelport say) and it
is rejected because the indentation is wrong or the variable names use the
wrong case - and the developer contributes to N projects, all with
different requirements for code style etc, how much time should the
developer be expected to spend on making everything 'perfect'.

I agree, making your code compliant to a certain coding style is a massive
waste of time. I think a good solution to that problem would be to invest
some time into clang-format once and have some automation to make
everything compliant.

**Comment by hkaiser** [comment]
> I agree, making your code compliant to a certain coding style is a massive waste of time.

For myself it is a measure of professionalism to be able to adapt my coding style to the file I'm editing. I don't like certain ways of how code is formatted myself - as everybody - but I try to do that. However I believe that the implementation of certain basic coding guidelines ensuring (at least) somewhat homogeneously formatted code is an expression of quality. 

The rule of thumb applied to HPX so far was that while editing existing files the author adapts his style to the pre-existing one. For new files the author tries to align as much as possible with the overall style, but Is free to go his own ways (again in certain limits).

> I think a good solution to that problem would be to invest some time into clang-format once and have some automation to make everything compliant.

@sithhell Sure, feel free to contribute a corresponding configuration file authors can apply manually to their files before initial check-in. 

I'd be against automatic reformatting all of the existing code, though - this would destroy the editing history and make tools like blame almost useless.

Non-correcting tools like `inspect` however are the way to go and should run on every build. These check both, some formal guidelines and some semantic things. The formal things (like 'no tabs', or 'no trailing whitespace') can be easily enforced without any effort by using [editorconfig](http://editorconfig.org/) (available for almost any editor). The semantic checks (use `std::move` instead of `boost::move`, etc.) help improving quality and portability and would require manual correction anyway.

That said - I was afraid that our discussion would turn into a bike shed about coding styles...
Other topics mentioned by @K-ballo are much more important, let's focus on those points.

**Comment by biddisco** [comment]
@hkaiser Do we simply start editing the https://github.com/STEllAR-GROUP/hpx/blob/master/CONTRIBUTING.md doc on github to address the main points, or do we create a doc via email or some other medium.

**Comment by sithhell** [comment]
Am 08.06.2015 2:15 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>>
>> I agree, making your code compliant to a certain coding style is a
massive waste of time.
>
> For myself it is a measure of professionalism to be able to adapt my
coding style to the file I'm editing. I don't like certain ways of how code
is formatted myself - as everybody - but I try to do that. However I
believe that the implementation of certain basic coding guidelines ensuring
(at least) somewhat homogeneously formatted code is an expression of
quality.

There is nothing I disagree with here, all I'm trying to say is that this
might be a tedious task getting in the way. If there are tools to help with
that, why not use them?

>
> The rule of thumb applied to HPX so far was that while editing existing
files the author adapts his style to the pre-existing one. For new files
the author tries to align as much as possible with the overall style, but
Is free to go his own ways (again in certain limits).
>>
>> I think a good solution to that problem would be to invest some time
into clang-format once and have some automation to make everything
compliant.
>
> @sithhell Sure, feel free to contribute a corresponding configuration
file authors can apply manually to their files before initial check-in.
>
> I'd be against automatic reformatting all of the existing code, though -
this would destroy the editing history and make tools like blame almost
useless.

Good point.

>
> Non-correcting tools like inspect however are the way to go and should
run on every build. These check both, some formal guidelines and some
semantic things. The formal things (like 'no tabs', or 'no trailing
whitespace') can be easily enforced without any effort by using
editorconfig (available for almost any editor). The semantic checks (use
std::move instead of boost::move, etc.) help improving quality and
portability and would require manual correction anyway.
>
> That said - I was afraid that our discussion would turn into a bike shed
about coding styles...
> Other topics mentioned by @K-ballo are much more important, let's focus
on those points.

Absolutely, however, I think the points raised by John are valid, we
shouldn't overcomplicate things to avoid turning away potential
contributors just because of formal issues with the code etc.

**Comment by K-ballo** [comment]
I see a lot of concern about keeping buildbot green as if it was the fundamental problem, while the utility of buildbot lies in those times when it is red, as long as those are brief. Even the slightest spot of red in buildbot means the codebase is broken and that something needs to be fixed (quickly, as it otherwise blocks progress on both developers and users), which is or should be the point of using buildbot in the first place.

Here are a few past scenarios in which a red buildbot was useful:

- Catching a regression
- Catching code that triggers errors on the supported platform (compiler bugs, missing features)
- Catching errors caused by differences in build flags (including different Boost versions)
- Catching race conditions

Here are a few past scenarios in which a red buildbot was a symptom of some other problem:

- Leaving a build broken by any of the above issues (often forcing others to stop what they are doing to fix it)
- Committing code with trivial syntax errors (at least those that would have been caught by the submitter's compiler had the code been built at least once)
- Committing code when circle-ci reveals errors, or before circle-ci even runs
- Merging PRs with standing feedback on how the code would break the build (before that feedback is addressed or even acknowledged)
- Using C++11/14 features in a way that is well known not to be compatible with the supported platform (could have been caught by review)
- Using features without even attempting to #include the headers in which those are declared

The more red means symptoms, the less useful buildbot becomes (to the extent that some deemed reasonable in the past to turn errors into warnings due to the noise).

**Comment by sithhell** [comment]
Am 08.06.2015 6:20 nachm. schrieb "Agustín Bergé" <notifications@github.com
>:
>
> I see a lot of concern about keeping buildbot green as if it was the
fundamental problem, while the utility of buildbot lies in those times when
it is red, as long as those are brief. Even the slightest spot of red in
buildbot means the codebase is broken and that something needs to be fixed
(quickly, as it otherwise blocks progress on both developers and users),
which is or should be the point of using buildbot in the first place.

Buildbot wasn't taken very seriously so far. There wasn't a single time
were we had a complete green build. I disagree that a red buildbot is
blocking process, you can just roll back to the last known working stage,
always. The problem is that it's hard to define that for us at the moment.

>
> Here are a few past scenarios in which a red buildbot was useful:
>
> Catching a regression
> Catching code that triggers errors on the supported platform (compiler
bugs, missing features)
> Catching errors caused by differences in build flags (including different
Boost versions)
> Catching race conditions
>
> Here are a few past scenarios in which a red buildbot was a symptom of
some other problem:
>
> Leaving a build broken by any of the above issues (often forcing others
to stop what they are doing to fix it)
> Committing code with trivial syntax errors (at least those that would
have been caught by the submitter's compiler had the code been built at
least once)
> Committing code when circle-ci reveals errors, or before circle-ci even
runs
> Merging PRs with standing feedback on how the code would break the build
(before that feedback is addressed or even acknowledged)
> Using C++11/14 features in a way that is well known not to be compatible
with the supported platform (could have been caught by review)
> Using features without even attempting to #include the headers in which
those are declared

Those things will always happen and luckily buildbot will catch them. Sure,
the things you describe here are all results of human error and always our
fault. Sticking closer to our process will help to eliminate them most of
the time, hopefully. Sadly, we are not perfect and I'd argue that it's not
the end of the world if that happens and we have to roll back a merge,
that's why we have version control systems. Furthermore, I'm glad that
buildbot catches those symptoms.

>
> The more red means symptoms, the less useful buildbot becomes (to the
extent that some deemed reasonable in the past to turn errors into warnings
due to the noise).

We never turned errors into warnings to reduce the noise. That's just a
wrong perception of the buildbot results.
A year or so, when making buildbot more modular and maintainable we wanted
to easily distinguish between failed builds and failed tests. Unfortunately
buildbot is only able to mark it as failed (red), successful(green) or with
warnings (orange). We decided to mark a run with failed tests with orange
and failed builds with red. The web ui has a legend to the color codes on
top, the irc bot unfortunately says "failed with warnings". The noise is
still the same. I personally like that distinction, though I can understand
if the poorly chosen wording is confusing to some degree. If yall think
this is useless, we can change it anytime. BTW, each failed tests is
reported separately in the build step for quite a while now.
Here is clearly a communication problem.

**Comment by K-ballo** [comment]
> Buildbot wasn't taken very seriously so far.

Indeed, that's precisely what brings me here today.

> I disagree that a red buildbot is
> blocking process, you can just roll back to the last known working stage,
> always.

A red buildbot has already been a blocking process. Users have come asking whether to bother using master, waiting for us to fix it or determine a revision for them to use, wondering if their problems could be explained by the red, etc. As a developer, a red buildbot has stopped me from moving ahead with my changes, rebasing them, testing them against master, and finally merging them. Others don't see merging changes to an already broken build as problematic, which means further work as I have to keep my own changes in sync and tested.

Reverting broken changes is always a possibility when those cannot be trivially fixed, or when they require further investigation. Once buildbot informs about a breakage, it's job its done. If the breakage is not addressed, then it simply becomes noise that gets in the way.

> Those things will always happen and luckily buildbot will catch them. Sure,
> the things you describe here are all results of human error and always our
> fault. Sticking closer to our process will help to eliminate them most of
> the time, hopefully. Sadly, we are not perfect and I'd argue that it's not
> the end of the world if that happens and we have to roll back a merge,
> that's why we have version control systems. Furthermore, I'm glad that
> buildbot catches those symptoms.

Some of those things should never happen. Others would still happen even if being a bit more careful, and that's what buildbot is there for (as I say in my previous reply). Others, unfortunately, will not always be caught by buildbot so there should be extra care with those (as they tend to become someone else's problem).

I see buildbot as a safety net, not a garbage collector.
 
> We never turned errors into warnings to reduce the noise. That's just a
> wrong perception of the buildbot results.
> A year or so, when making buildbot more modular and maintainable we wanted
> to easily distinguish between failed builds and failed tests. 

I keep hearing different reasons for why the change was made. Just last week I was told that there is no intention to treat failed builds and failed tests differently as they both are signals of a broken codebase, and that fixing those racy tests that have been randomly popping up for about two years was the only thing standing in the way of treating errors as errors again.

**Comment by hkaiser** [comment]
> Just last week I was told that there is no intention to treat failed builds and failed tests differently as they both are signals of a broken codebase

Nobody has said that. @Finomnis decided unilaterally to keep it the way as it is even after we asked him to change it.

> and that fixing those racy tests that have been randomly popping up for about two years was the only thing standing in the way of treating errors as errors again.

Not sure where this comes from. Nobody has communicated this either (AFAIK).

**Comment by K-ballo** [comment]
> and that fixing those racy tests that have been randomly popping up for about two years was the only thing standing in the way of treating errors as errors again.
> 
> Not sure where this comes from. Nobody has communicated this either (AFAIK).

[29 May 15 09:59] * mstumpf: K-ballo: orange=tests fail
[29 May 15 09:59] * mstumpf: K-ballo: and you know why? because we still didn't manage to remove the random race condition that sometimes lets tests fail
[29 May 15 09:59] * mstumpf: K-ballo: as soon as you find it, i will change it to red

**Comment by Finomnis** [comment]
That's not quite right, I would surely change it if that's what you guys
want. I just tried to communicate that it makes the buildbot a lot more
readable of we have two different colors. I don't get why we don't want to
use different colors if we have them?
