### ISSUE TITLE
hpx::parallel does not have a sort implementation

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#1836]
@fjtapia has created parallel sort algorithms which can be modified to work with HPX. 

Here are the algorithms related to sort:
- [x] sort (#1850)
- [x] sort_by_key (#1956)
- [x] partial_sort (#5041)
- [x] partial_sort_copy (#5630)
- [x] stable_sort (#4803)
- [x] nth_element (#5592)

**Comment by fjtapia** [comment]
The file needed for to use the algorithms is hpx/parallel/sort/sort.hpp.
In this file you have a sort , and  stable_sort algorithms. If in the invocation, if  use   hpx::parallel::parallel_execution_policy  you are calling to the parallel version and if use the hpx::parallel::sequential_execution_policy you are calling to a single thread version of the algorithm.
You have an invocation example in benchmark/LinuxGCC/bench/fast_benchmark.cpp.
Internally, the algorithms use different names. The sort with 1 thread is introsort, the parallel version is parallel_sort,  the stable sort is spin_sort, and the parallel version is parallel_stable_sort . You can find in hpx/parallel/sort/algorithms

**Comment by hkaiser** [comment]
Thanks Francisco. I assume you're talking about this repository: https://github.com/fjtapia/HPX_sort.

**Comment by hkaiser** [comment]
The branch [parallel_sort](https://github.com/STEllAR-GROUP/hpx/tree/parallel_sort) can be used to integrate this into HPX.

**Comment by biddisco** [comment]
I have already begun a branch fixing_1836 which I'll push soon. I have removed most of Francisco's hand coded introsort and just kept the parallel dataflow wrapper around a std::sort. it gives almost the same performance (<5% diff) on all the configurations I've tested so far, but does not require the inclusion of many extra files. I'm still cleaning it all up. I've actually gone back to the original repo of Francisco in git@github.com:fjtapia/sort_parallel.git because the changes in the HPX_sort repo broke the stuff I was already working on and for now, I only need sort The other stuff can be added back in gradually once the initial code is in the main repo (i.e. add back stable sort and then look into a decent merge-sort implementation). Indirect sort - or SortByKey is also on the list.
(NB. I'm not sure if all std::sort implementations use intro-sort), but for now it'll do.

**Comment by hkaiser** [comment]
@biddisco Sure, The parallel_sort branch was not meant to duplicate any work. My goal was to develop the concepts we need to make the exposed API work. I also started to add the API docs.

**Comment by biddisco** [comment]
I would like to add sort_by_key to the list as it is an extremely useful addition to the algorithms. (thrust has such an implementation)
- [x] sort (#1850)
- [ ] sort_by_key
- [ ] partial_sort,  partial_sort_copy   
- [ ] stable_sort
- [ ] nth_element

**Comment by K-ballo** [comment]
Wouldn't `sort_by_key` just be `sort` with a projection?

**Comment by biddisco** [comment]
yes, currently it would require range-v3 library, but until then, I have an implement using a specialized zip iterator

**Comment by K-ballo** [comment]
AFAIK our implementation already supports projections https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/parallel/algorithms/sort.hpp#L375-L378

All algorithms with predicates should.

**Comment by hkaiser** [comment]
@K-ballo we're working on adding those, currently. But `parallel::sort` already has it.

**Comment by biddisco** [comment]
I was/am not sure how to use the projections without the range library, feel free to remove the tuple_iterator stuff from the sort_by_key branch and replace it with a projection using zip iterators.

**Comment by biddisco** [comment]
NB. I only added a simple pairwise sort, but in principle a zipped tuple of arbitrary numbers of value arrays can be supported. I didn't need them at the moment so thought I'd start with just a pair interface.

**Comment by biddisco** [comment]
I'd like to know if any of the work on projections/ranges makes it now possible to have a native sort_by_key in HPX or if the sort_by_key implementation (ref 001fcb7f441ac32a2f1f208af2833e0ffb04db4f ) is of use.

**Comment by hkaiser** [comment]
I've created a small example demonstrating how `sort_by_key()` can be implemented on top of the existing `hpx::parallel::sort()` [here](https://github.com/STEllAR-GROUP/hpx/blob/sort_by_key_example/examples/quickstart/sort_by_key.cpp).

**Comment by fjtapia** [comment]
Hi,

happy new year for all.

In the actual version of the HPX::sort you have the tools for to do a index
sort, in tools/util_iterator inside the file util_iterator.hpp, you have
the struct


template < class iter_t,

class comp_t =std::less<typename iter_value<iter_t>::type> >

struct less_ptr_no_null

{ //----------------------------- Variables -----------------------

   comp_t comp ;

//----------------------------- Functions ----------------------

inline less_ptr_no_null ( comp_t C1 = comp_t()):comp(C1){};

inline bool operator ()( iter_t T1, iter_t T2 ) const

{ //-------------------- begin ------------------------------

return comp(*T1 ,*T2);

};

};


The idea is to generate a vector of pointers or iterators, and this object
is the comparison object. For to construct receives an object for to
compare two objects.


After this you can sort with any algorithm.


You have many examples, because all the algorithms inside the algorithm
folder have an indirect version.


The indirect version create a vector of iterators, and with the
less_ptr_no_null struct sort the elements, and after all sort the elements
according with the index with the sort_index function.


If you delete the sort_index of these functions you have index sort


template < class iter_t >

void indirect_parallel_sort (iter_t first, iter_t last)

{ //------------------------------- begin--------------------------

typedef std::less <typename iter_value<iter_t>::type> compare ;

typedef less_ptr_no_null <iter_t, compare> compare_ptr ;


std::vector<iter_t> VP ;

create_index ( first , last , VP);

parallel_sort ( VP.begin() , VP.end(), compare_ptr() );

sort_index ( first , VP) ; // if you delete this line you have an index sort

};

2016-01-02 19:17 GMT+01:00 Hartmut Kaiser <notifications@github.com>:

**Comment by biddisco** [comment]
so what do we do about sort_by_key then? I would like to use it, the sort_by_key branch gets around the zip_iterator problem by using a ton of bloaty iterator code we don't really want (and I did not check much), but the out of the box stuff is no good directly (yet?). The solution from @fjtapia wastes memory by using an index array, but would be a reasonable fall back for the case when the objects to be sorted are very large and many swaps would be expensive so using an index array might be prefereable.

**Comment by hkaiser** [comment]
@biddisco As explained by @K-ballo on IRC, the example I added can't work today, which is a pity. The reason is that the type returned by zip_iterator is an rvalue (conceptually, a `tuple<KeyValueType&, ValueType&>&&`) which can't be bound to the lvalues expected by swap. 

Note that the example works on MSVC, though because the compiler happily binds the rvalues to lvalues.

Let me look at your iterator-bloat one more time, there might be a workaround in there we can apply for now.

**Comment by biddisco** [comment]
yes. I am aware of the problems - if you are able to extract a minimal set of useful functions from the bloaty code, that'd be great.

**Comment by fjtapia** [comment]
Hi,


I am a bit confused about the concept of index, please clarify me.

I understand as index a collection of pointers, iterators or any other
mechanism for to pointer to the elements. This collection can be sorted
without move the elements, and permit a binary search by the condition used
for to search.


The index permit to have a collection of data be sorted by several concepts
simultaneously.

A sort example show my idea and how to use:



struct member
{    uint32_t num ;
    std::string name;
    float weight;
};
typedef typename vector<member>::iterator iter_t ;

struct cmp_num
{    bool operator() ( const member &m1, const member &m2) const
    {    return ( m1.num < m2.num); };
};

struct cmp_name
{    bool operator() ( const member &m1, const member &m2)const
    {    return ( m1.name < m2.name); };
};

struct cmp_weight
{    bool operator() ( const member &m1, const member &m2) const
    {    return ( m1.weight < m2.weight); };
};

ostream & operator << ( ostream & out, const member &m)
{    out<<m.num<<" - "<<m.name<<" - "<<m.weight<<endl;
    return out ;
};

int main( int, char*[] )
{   //------------------------ begin -----------------------
    // The data are sorted by number
    vector<member> VM = { {1,"Peter",85.6},   {2,"Hanna", 63.4 },
                        {3,"John", 83.6},     {4,"Elsa",56.6} };
    vector<iter_t> Ix_name, Ix_weight ;

    for ( iter_t it= VM.begin() ; it != VM.end() ; ++it)
    {    Ix_name.push_back ( it);
        Ix_weight.push_back( it);
    };

    typedef less_ptr_no_null <iter_t, cmp_name>       compare_name ;
    typedef less_ptr_no_null <iter_t, cmp_weight>     compare_weight ;

    sort::introsort (Ix_name.begin(), Ix_name.end(),compare_name());

    sort::introsort (Ix_weight.begin(), Ix_weight.end(),compare_weight());

    cout<<"Printing sorted by number \n";
    for (auto it = VM.begin(); it != VM.end() ; ++it) cout<<(*it);

    cout<<"Printing sorted by name \n";
    for (auto it = Ix_name.begin(); it != Ix_name.end() ; ++it)
cout<<(*(*it));

    cout<<"Printing sorted by weight \n";
    for (auto it = Ix_weight.begin(); it != Ix_weight.end() ; ++it)
cout<<(*(*it));

    return 0;
};

The results obtained are

Printing sorted by number
1 - Peter - 85.6
2 - Hanna - 63.4
3 - John - 83.6
4 - Elsa - 56.6
Printing sorted by name
4 - Elsa - 56.6
2 - Hanna - 63.4
3 - John - 83.6
1 - Peter - 85.6
Printing sorted by weight
4 - Elsa - 56.6
2 - Hanna - 63.4
3 - John - 83.6
1 - Peter - 85.6

If I am wrong, please clarify me.

2016-01-02 21:57 GMT+01:00 John Biddiscombe <notifications@github.com>:

**Comment by Jedi18** [comment]
Hi @fjtapia ! Do you plan to contribute the remaining partial_sort_copy and nth_element anytime soon? Would really appreciate your help.

**Comment by fjtapia** [comment]
Hi *Akhil*


I will finish in a few weeks the partial_sort_copy and the other functions
in HPX.

Today I am working in a new parallel sort algorithm, simple and fast, which
permit an easy implementation of these functions in parallel mode, and, of
course, the parallel sort.

Now I am testing and tuning the algorithm, primarily for the Boost Sort
library, and after, for HPX.

Thanks by your interest


Francisco

**Comment by hkaiser** [comment]
> Hi *Akhil* I will finish in a few weeks the partial_sort_copy and the other functions in HPX. Today I am working in a new parallel sort algorithm, simple and fast, which permit an easy implementation of these functions in parallel mode, and, of course, the parallel sort. Now I am testing and tuning the algorithm, primarily for the Boost Sort library, and after, for HPX. Thanks by your interest Francisco

Thanks Francisco, much appreciated!

**Comment by hkaiser** [comment]
This has been fixed
