### ISSUE TITLE
Exception in primary_namespace::resolve_free_list

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#2122]
When running octotiger on 128 nodes at high resolution, I get this bug:
```
{what}: primary_namespace::resolve_free_list, failed to resolve gid, \
    gid({0000000700000001, 000000000b9815bc}): HPX(internal_server_error)
```
Full output is here:

https://gist.github.com/dmarce1/ff9b28e9b8f0d0d288ee6e557ec6fe8a

**Comment by hkaiser** [comment]
So something is definitely off with the garbage collection code. This error means something is free'd twice.

**Comment by sithhell** [comment]
Am 26.04.2016 8:41 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>
> So something is definitely off with the garbage collection code. This
error means something is free'd twice.

I was seeing a double free as well with the split_credit test (different
symptoms though).

**Comment by dmarce1** [comment]
I just ran the same thing over again and it failed with the same error on the first timestep.

This tarball has the executable and the core dump from the process HPX says caused the fault:
https://drive.google.com/file/d/0B_Hf1bEwvJEkbDMtMnRwRFFNbHc/view?usp=sharing

**Comment by hkaiser** [comment]
@dmarce1 Is this reproducible now?

**Comment by dmarce1** [comment]
This is a 128 node run. I've been able to run it twice - the first time this error turned up after a couple hundred timesteps - the second time it turned up immediately. I will try and get a 128 node interactive session to see how reliably it comes up. I could run it in a loop, but not without core dumps, as the core dump files are huge.

**Comment by dmarce1** [comment]
I think this issue and the one here: https://github.com/STEllAR-GROUP/hpx/issues/2108 must be the same bug

**Comment by hkaiser** [comment]
@dmarce1 I agree, I think that all the problems you're seeing are a variation of the cause. I've been thinking a lot about this lately and I now believe that it is not a race condition causing this. It's it caused by an occasional out of order execution of credit-increment and credit-decrement operations. This would explain essentially all of the errors we're seeing: negative ref-counts, apparently duplicate object deletions, apparently non-existing gid mappings, etc. The question is under what circumstances does this happen? I will continue staring at the relevant pieces of code hoping to spot the problem. As long as we're not able to make it reproducible that's the only choice we have.

**Comment by dmarce1** [comment]
Is it useful to have more core dumps? The core dump files can be very large, ~5 gigabytes for each node = 640 GB for a 128 node dump.

**Comment by hkaiser** [comment]
@dmarce1 Please try again using master. We have just merged a fix which has caused problems for two other applications suffering from similarly rare race conditions in their code (see #2165).

**Comment by sithhell** [comment]
We can close this once #2223 is merged.

**Comment by hkaiser** [comment]
#2223 has been merged. This should be fixed, pleasse reopen if necessary.
