### ISSUE TITLE
Error while compiling on Mac + boost 1.60

### ISSUE THREAD

**Issue by ktf** [STEllAR-GROUP/hpx#2170]
Using the current (4324defe863c07f5d9dd8b1b27f11f0747717bee) master on Mac fails to compile with:

```
DEBUG:hpx:0: /opt/boxen/homebrew/opt/boost/include/boost/context/execution_context.ipp:61:5: error: thread-local storage is not supported for the current target
DEBUG:hpx:0:     thread_local static ptr_t   current_rec;
DEBUG:hpx:0:     ^
```

```
boost: 1.60

Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by hkaiser** [comment]
This is a known issue which is caused by a problem in Boost V1.60 (and Boost V1.58, btw). All other versions of Boost seem to work fine (including the just released 1.61). Unfortunately, there is nothing we can do about that (see also #2026 or #2137 for more information). 

Please either update Boost to V1.61 or downgrade to an older version for compilation on Mac OS/X.
