### ISSUE TITLE
For loop doesn't parallelize

### ISSUE THREAD

**Issue by mcopik** [STEllAR-GROUP/hpx#2281]
The example shown at the website:
http://stellar-group.org/2016/03/hpx-and-index-based-cpp-parallel-loops/
Suggests that the input to for_loop may be a pair of integers giving the range of computations. 

However, in the implementation the iterator type is passed to traits:
https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/parallel/algorithms/for_loop.hpp#L235
Which always gives false; int is not an iterator type, hence an integer can't be a forward iterator:
https://github.com/STEllAR-GROUP/hpx/blob/72e9be0e6c135e587cc0975099f233bac7dcfc97/hpx/traits/is_iterator.hpp#L59

The is_seq integral constants is true which prevents from using a parallel execution policy even when it's explicitly specified. I've encountered this problem when working with Safura on her code and trying to find a reason why the code parallelize so poorly, when it doesn't parallelize at all.

**Comment by hkaiser** [comment]
Could you create a small reproducing test case to demonstrate the problem, please?

**Comment by mcopik** [comment]
In Safura's code we had a problem with sequential execution, but I can't reproduce this problem in a smaller example because for_loop ends with throwing an exception: HPX(invalid_status) (maybe it's similar with the issue #2282). It executes correctly with the sequential executor:
https://gist.github.com/mcopik/1c0426d15189a777376f83e5f4ec7406

Am I doing something wrong here?

**Comment by hkaiser** [comment]
@mcopik Could you please describe:

- how you built HPX
- what tests (code) to build and how to run it in order to reproduce the issue

I'm not sure from you description of what code you ran (you mention at least two different scenarios, both not well described) and what errors you have seen when running any of those.

What is 'Safura's code', etc.?

In other words, please create a minimal reproducing test case I can cut&paste, compile, and run in order to see what's going on.
