### ISSUE TITLE
Change default number of threads used to the maximum of the system

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [STEllAR-GROUP/hpx#2324]
Please change the default number of threads so that all cores are utilized.

If no configuration is provided, HPX falls back to its defaults. Those lead to only a single core being used on a node (developer desktop machine). For an easier start for new developer, it would be nice if by default the number of threads would match the number of cores.

**Comment by pagrubel** [comment]
Hmm I’m wondering what the default really is. For instance if I run hello_world (examples/quickstart/hello_world) on the head node on rostam it only uses one three whereas if I make an interactive allocation on another node such as carson, it use all 20 threads as default.

Pat
On Sep 7, 2016, at 5:01 PM, DavidPfander-UniStuttgart <notifications@github.com<mailto:notifications@github.com>> wrote:


Please change the default number of threads so that all cores are utilized.

If no configuration is provided, HPX falls back to its defaults. Those lead to only a single core being used on a node (developer desktop machine). For an easier start for new developer, it would be nice if by default the number of threads would match the number of cores.

**Comment by pagrubel** [comment]
On Sep 7, 2016, at 5:40 PM, Patricia Grubel <pagrubel@nmsu.edu<mailto:pagrubel@nmsu.edu>> wrote:

Hmm I’m wondering what the default really is. For instance if I run hello_world (examples/quickstart/hello_world) on the head node on rostam it only uses one three whereas if I make an interactive allocation on another node such as carson, it use all 20 threads as default.

one thread (stupid auto correct got me)

Pat
On Sep 7, 2016, at 5:01 PM, DavidPfander-UniStuttgart <notifications@github.com<mailto:notifications@github.com>> wrote:


Please change the default number of threads so that all cores are utilized.

If no configuration is provided, HPX falls back to its defaults. Those lead to only a single core being used on a node (developer desktop machine). For an easier start for new developer, it would be nice if by default the number of threads would match the number of cores.

**Comment by pagrubel** [comment]
Ok so one shouldn’t run on the head node anyway.

Pat
On Sep 19, 2016, at 9:40 AM, DavidPfander-UniStuttgart <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Pat,
I talked to Al about the default number of threads and cores used on rostam. There seems to be a class that interprets the slurm environment to setup HPX according to those variables.

David

**Comment by sithhell** [comment]
Am 19.09.2016 5:40 nachm. schrieb "DavidPfander-UniStuttgart" <
notifications@github.com>:
>
> Hi Pat,
> I talked to Al about the default number of threads and cores used on
rostam. There seems to be a class that interprets the slurm environment to
setup HPX according to those variables.

There is indeed. Not only for slurm but other batch systems as well. In
addition, you can always pass --hpx:threads=all (even in your program).
Does this solve your issue?

**Comment by DavidPfander-UniStuttgart** [comment]
Yes, I'm aware that this switch lets my use all cores. However, when I developed my very first small example problem, I wasn't aware of that switch und didn't encounter any obvious hints that this extra switch is necessary. Therefore, I was surprised that my application didn't run in parallel.

To make it easier to start developing stuff with HPX, I merely wanted to propose that, if no other configuration is set, all threads are used by default.

Similarly, OpenMP uses all threads by default, although the number of threads can be controlled via OMP_NUM_THREADS.

**Comment by sithhell** [comment]
This has been resolved after merging #2789
