### ISSUE TITLE
Can't wait on a wrapped future

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/hpx#2370]
I create a simple wrapped future in the attached file. It uses a sleep(1) to ensure that the lambda function doesn't complete too quickly to see the probem. The problem is that the wait() call completes, before the wrapped future finishes, thus the code prints:

finish
I am done

instead of:

I am done
finish

The way things stand, there seems to be no way to wait on a wrapped future.

**Comment by stevenrbrandt** [comment]
I thought I'd attached that code. Apparently the web interface tricked me.

**Comment by hkaiser** [comment]
The code does the correct thing. The problem is that `async(run)` returns a `future<future<void>>`, so that `async(run).wait()` will just wait for the outer future to become ready. The outer future however becomes ready when `run()` has executed to completion. In order to achieve the effect you are looking for you'd need to change the code to:

    async(run).get().wait();

alternatively (forcing implicit unwrapping):

    future<void> f = async(run); f.wait();

I hope that explains things.
