### ISSUE TITLE
Template compilation error using HPX_WITH_DATAPAR_LIBFLATARRAY

### ISSUE THREAD

**Issue by BryantLam** [STEllAR-GROUP/hpx#2394]
Building git commit 88af985 with HPX_WITH_DATAPAR_LIBFLATARRAY=ON.

This header file generated GCC compiler errors: 
hpx/parallel/traits/detail/libflatarray/vector_pack_alignment_size.hpp
`60:44: error: expected primary-expression before > token`
`60:45: error: '::ALIGNMENT' has not been declared`
`69:44: error: expected primary-expression before > token`
`69:45: error: '::ALIGNMENT' has not been declared`

Resolution was to change lines 60 and 69
from `shortvec::strategy::alignment<T>::ALIGNMENT`
to `shortvec::strategy::template alignment<T>::ALIGNMENT`

This bug may affect the other hpx/parallel/traits/detail/* implementations as well.

**Comment by hkaiser** [comment]
Thanks, this is currently not fully implemented because of missing pieces in libflatarray. Please don't use this option at this point. We hope to have this finalized before releasing V1.0.

Both, HPX_WITH_DATAPAR_VC` and `HPX_WITH_DATAPAR_BOOST_SIMD` should be fine, though, especially on the branch datapar_octotiger (PR #2388). Please report any problems you may find there.

@gentry: Do you have a estimated timeline for libflatarray becoming usable here?

**Comment by hkaiser** [comment]
@gentryx  Is this something you would consider fixing in libflatarray? Or should we remove the attempts of integrating it with HPX and close this ticket instead?
