### ISSUE TITLE
CMAKE failed because it is missing:  TCMALLOC_LIBRARY TCMALLOC_INCLUDE_DIR

### ISSUE THREAD

**Issue by Rabab53** [STEllAR-GROUP/hpx#2524]
I am trying to build hpx with the following command it cause an error as follow:
cmake .. -DBOOST_ROOT=/usr/lib/x86_64-linux-gnu/  -DHWLOC_ROOT=/home/runtime_systems/hwloc-1.10.1/install/lib -DCMAKE_INSTALL_PREFIX=/home/runtime_systems/hpx/install

build failed as follow:
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Could NOT find TCMalloc (missing:  TCMALLOC_LIBRARY TCMALLOC_INCLUDE_DIR) 
CMake Error at cmake/HPX_Message.cmake:43 (message):
  ERROR: HPX_WITH_MALLOC was set to tcmalloc, but tcmalloc could not be
  found.  Valid options for HPX_WITH_MALLOC are: system, tcmalloc, jemalloc,
  tbbmalloc, and custom
Call Stack (most recent call first):
  cmake/HPX_SetupAllocator.cmake:29 (hpx_error)
  CMakeLists.txt:1308 (include)

-- Configuring incomplete, errors occurred!
See also "/home/runtime_systems/hpx/my_hpx_build/CMakeFiles/CMakeOutput.log".
See also "/home/runtime_systems/hpx/my_hpx_build/CMakeFiles/CMakeError.log"

Any advice on how to solve it?

Thanks,
Rabab

**Comment by sithhell** [comment]
Hi Rabab,

The error message says:
ERROR: HPX_WITH_MALLOC was set to tcmalloc, but tcmalloc could not be
  found.  Valid options for HPX_WITH_MALLOC are: system, tcmalloc, jemalloc,
  tbbmalloc, and custom

The resolution is as as simple as either switching the allocator (system does 
not have any additional dependencies) or install the necessary packages. 
Either by hand or from your linux distribution. tcmalloc is often found as 
part of gpertools, based on the distribution, you might need to install the -
dev packages as well.

**Comment by hkaiser** [comment]
@Rabab53 to clarify: try using `cmake -DHPX_WITH_MALLOC=system ...`

**Comment by hkaiser** [comment]
@sithhell we should probably change our build system to fall back to `system` if `tcmalloc` is not available.

**Comment by sithhell** [comment]
On Montag, 27. Februar 2017 12:52:53 CET Hartmut Kaiser wrote:
> @sithhell we should probably change our build system to fall back to
> `system` if `tcmalloc` is not available.
 
I am opposing that. I played with that thought for a long time but dismissed 
it. The rationale is that we shouldn't silently fall back to a suboptimal 
solution, I was hoping that the error message is clear enough. 

While I agree that defaulting to tcmalloc is arbitrary, the need for a high 
performance malloc implementation is absolutely there so I chose to have a 
hard failure to make the user aware of the implications instead of silently 
falling back to a solution which might lead to bad performance.

We might need to document it more prominently here:
http://stellar-group.github.io/hpx/docs/html/hpx/manual/build_system/
prerequisites.html

**Comment by hkaiser** [comment]
Ok, fair enough.

**Comment by biddisco** [comment]
Since it is very easy to install jemalloc, and it gives as good, or better performance as tcmalloc, we could simply extend the error message to output the following

You have requested a non system malloc, but it was not found, you may install jemalloc as follows 
```
JEMALLOC_VER=4.4.0
wget https://github.com/jemalloc/jemalloc/releases/download/$JEMALLOC_VER/jemalloc-$JEMALLOC_VER.tar.bz2
tar -xjf jemalloc-$JEMALLOC_VER.tar.bz2
cd jemalloc-$JEMALLOC_VER
./autogen.sh --prefix=$HOME/local/jemalloc/$JEMALLOC_VER
make -j -k install
```
and invoke cmake with the extra options
```
cmake -DHPX_WITH_MALLOC=JEMALLOC -DJEMALLOC_ROOT=$HOME/local/jemalloc/$JEMALLOC_VER
```
and update the error message from time to time when a newer jemalloc is available

**Comment by hkaiser** [comment]
I'd rather put a (stable) link to our documentation into the error message where this is described in detail.

**Comment by Rabab53** [comment]
Thanks all

**Comment by hkaiser** [comment]
@Rabab53 Can we close this issue now? Has it been resolved for you?

**Comment by hkaiser** [comment]
@ZiCog as @sithhell said above, you might have to install the -dev packages, depending on your distro.

**Comment by prlw1** [comment]
I see where @ZiCog is coming from... on Ubuntu 18.04.2:
```
$ sudo apt search tcmalloc 
Sorting... Done
Full Text Search... Done
libtcmalloc-minimal4/bionic,now 2.5-2.2ubuntu3 amd64 [installed]
  efficient thread-caching malloc
$
```
(and cmake fails to find TCMalloc)

There are no -dev packages.

```
$ sudo apt search jemalloc 
Sorting... Done
Full Text Search... Done
libjemalloc-dev/bionic 3.6.0-11 amd64
  development files and documentation for jemalloc

libjemalloc1/bionic 3.6.0-11 amd64
  general-purpose scalable concurrent malloc(3) implementation
```
and
```
$ sudo apt install libjemalloc-dev
...
$ cmake -DHPX_WITH_MALLOC=jemalloc ...
```
does the trick.

**Comment by hkaiser** [comment]
A simple google search would have revealed that the corresponding `-dev` package on Ubuntu is named `libgoogle-perftools-dev`.

**Comment by rakeshsagalagatte** [comment]
@ZiCog  I'm using Arch destro [manjaro]. Here I installed `gperftools` package to satisfies the `tcmalloc` dependencies. 
`sudo pacman -S gperftools` .
