### ISSUE TITLE
Resource manager design for many core and heterogeneous machines

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2609]
We are in need of a resource manager to handle the way we allocate cores/sockets/gpus etc in a more user friendly and adjustable way.
@shoshijak is workin on a new resource manager and I have some ideas on how I'd like to use it

One basic design idea I have would look something like the following where I might want to assign the all even numbered PUs, on the 1st core of each socket to one thread pool, and the rest to another, but pu 0 , core 0 on socket 0 to a network only task pool.
```c++
int main() {
    auto rm = hpx::get_resource_manager(); // queries hwloc interally for into
    auto pool_1 = rm.create_thread_pool("even_pool");
    auto pool_2 = rm.create_thread_pool("default_pool");
    auto pool_3 = rm.create_thread_pool("network");
    for (auto s : rm.sockets()) {
        for (auto c : s.cores()) {
            for (auto pu : c.pus()) {
                if (s.index()==0 && c.index==0 && pu ==0) {
                    pool_3.add(pu);
                }
                else if (s.index()==1 && pu %2 ==0) {
                    pool_1.add(pu);
                else (pu %2 ==0) {
                    pool_2.add(pu);
            }
        }
    }
    hpx_init(&etc);
}

int hpx_main(...) {
    auto network_executor = rm.executor_for_pool("network");
    auto f1 = hpx::async(network.executor, some_network_stuff);
    auto even_executor = rm.executor_for_pool("even_pool");
    auto default_executor = rm.executor_for_pool("default_pool");
    // tasks spawned without an executor will go onto the default pool
    //etc
}
```
the idea is that the user can partition the system up according to desire and create 'pools' of hardware threads that each run their own scheduler on.
A user who needs an executor for network, another for some gpu related activity (but using tasks on the cpu), and another exetutor, might need 3 pools - and on a single core system would oversubscribe by adding the same core to 3 pools. The resource manager would create 3 threads on the same core.

likewise we might iterate over GPUs in the same way, also NUMA domains instead of or as well as sockets.

Other features we would like.
The ability to ask for a core on a socket that is connected to the PCI bus that connects to the network card.
Same for GPU
Other hardware related issues of a similar theme. How do we specify a core on a socket closest to the PCI bus for the network? Can we specify the first PU on the first core on the socket closest to the network card using a syntax like
```c++
network_pool.add(rm.sockets.get(hpx::policies::resources::PCI).core(0).pu(0));
```
This issue should be the place to submit API ideas for how we implement the resource manager

Also : Resizing pools during/after program segments. reallocating resources etc. TBD

**Comment by sithhell** [comment]
The problem with partitioning up the system before hpx_init is that we
don't know if a node hosts more then one locality. Other than that, I like
the basic idea.

Am 05.05.2017 2:33 nachm. schrieb "John Biddiscombe" <
notifications@github.com>:

We are in need of a resource manager to handle the way we allocate
cores/sockets/gpus etc in a more user friendly and adjustable way.
@shoshijak <https://github.com/shoshijak> is workin on a new resource
manager and I have some ideas on how I'd like to use it

One basic design idea I have would look something like the following where
I might want to assign the all even numbered PUs, on the 1st core of each
socket to one thread pool, and the rest to another, but pu 0 , core 0 on
socket 0 to a network only task pool.

int main() {
    auto rm = hpx::get_resource_manager(); // queries hwloc interally for into
    auto pool_1 = rm.create_thread_pool("even_pool");
    auto pool_2 = rm.create_thread_pool("default_pool");
    auto pool_3 = rm.create_thread_pool("network");
    for (auto s : rm.sockets()) {
        for (auto c : s.cores()) {
            for (auto pu : c.pus()) {
                if (s.index()==0 && c.index==0 && pu ==0) {
                    pool_3.add(pu);
                }
                else if (s.index()==1 && pu %2 ==0) {
                    pool_1.add(pu);
                else (pu %2 ==0) {
                    pool_3.add(pu);
            }
        }
    }
    hpx_init(&etc);
}
int hpx_main(...) {
    auto network_executor = rm.executor_for_pool("network");
    auto f1 = hpx::async(network.executor, some_network_stuff);
    auto even_executor = rm.executor_for_pool("even_pool");
    auto default_executor = rm.executor_for_pool("default_pool");
    // tasks spawned without an executor will go onto the default pool
    //etc
}

the idea is that the user can partition the system up according to desire
and create 'pools' of hardware threads that each run their own scheduler on.
A user who needs an executor for network, another for some gpu related
activity (but using tasks on the cpu), and another exetutor, might need 3
pools - and on a single core system would oversubscribe by adding the same
core to 3 pools. The resource manager would create 3 threads on the same
core.

likewise we might iterate over GPUs in the same way, also NUMA domains
instead of or as well as sockets.

Other features we would like.
The ability to ask for a core on a socket that is connected to the PCI bus
that connects to the network card.
Same for GPU
Other hardware related issues of a similar theme. How do we specify a core
on a socket closest to the PCI bus for the network? Can we specify the
first PU on the first core on the socket closest to the network card using
a syntax like

network_pool.add(rm.sockets.get(hpx::policies::resources::PCI).core(0).pu(0));

This issue should be the place to submit API ideas for how we implement the
resource manager

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/STEllAR-GROUP/hpx/issues/2609>, or mute the thread

**Comment by hkaiser** [comment]
In order to support an arbitrary amount of executors we should not leave assigning concrete cores/processing units to the user. This will not scale. I think we should leave the task of deciding what cores/processing units to assign to what executor should be left to the resource manager (that's its main task). We should however have a means of defining constraints allowing to fine tune thread placement. So the executor should be able to ask the resource manager for exclusive/shared access to N cores/processing units with additional constraints, like 'N cores on the same socket' or '2 processing units on this core' etc. It is the task of the resource manager to either satisfy the request or to deny it if the request can't be satisfied.

**Comment by shoshijak** [comment]
And how would you let the user inform the executor of the kind/amount of resources he should request from the resource manager?

**Comment by hkaiser** [comment]
@shoshijak that should be part of the API exposed by the resource manager. I think the best way would be to define a interface the resource manager can use to interact with the requesting executor (see for instance: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/threads/thread_executor.hpp#L127-L146). This would be necessary also for implementing dynamic assignment of cores.

In short, a requesting executor would create an object exposing this interface and hand it to the resource manager. The resource manager in turn uses this interface to a) query the executor for constraints, requirements, etc. and b) to interact with the executor in order to grant or revoke access to a particular core/processing unit, and c) to extract statistics which can be used to assess how busy a particular executor currently is (needed in situations where more resources are requested than there are available).

**Comment by biddisco** [comment]
@hkaiser The idea outlined above was for when the user wants to customize things. By default, the resource manager will create a thread pool with all cores in (or however many asked for by hpx:threads).
The intention here was to provide a mechanism for the user to create differnt thread pools so that different schedulers can be run on each

**Comment by shoshijak** [comment]
After videoconf with @biddisco and @hkaiser, a summary of the plan:

- @biddisco's proposal and @hkaiser's proposal are very different, and are actually two different kinds of resource managers. Let's rename John's proposal "resource partitioner".
- The plan is to start by implementing a static resource partitioner, which more or less exposes the API described at the beginning of this thread, and which sits outside of the HPX runtime.
- Then move on either to allowing this resource partitioner to resize thread_pools dynamically during execution, or create a resource manager in @hkaiser's vision.

**Comment by shoshijak** [comment]
@biddisco and I are thinking some more about how the resource_partitioner would be used, and realized there are many potential conflicts between command-line specifications (e.g. `--hpx:threads N`, `--hpx:cores N` and `--hpx:bind`) and the code we suggest to allow in `int main()` (cf snippet at the top of this issue).

What do you think for example of the following question: 
If a user specifies `--hpx:threads N --hpx:bind balanced` on a two socket-machine where each socket has N PUs (so the machine has twice as many PUs as the user asked for in the command line). Suppose the user then asks for more than N PUs in` int main()`. 

should ... 

1) the resource partitioner fulfill this request even though it violates the command-line option?
2) the resource partitioner throw an exception and let the command line specifications override the code in `int main()` 
3) should `--hpx:threads` merely specify the number of OS-threads to put in the default pool (a thread-pool which contains all resources the user has not requested in `int main()` )?

**Comment by shoshijak** [comment]
And a different but related question: 
Should the resource-partitioner behave according to policies specified in the command line? 

Examples of policies could include 

- allow empty pools (or not)
- create a default pool (or not) 
- allow oversubscription (or not) 

any other ideas?

**Comment by biddisco** [comment]
@shoshijak The point I was trying to make earlier when we spoke was that if the user specified
`--hpx:threads=12 --bind=balanced` on a amchine with 2 12 core sockets, then when the iterators are created in the resource manager, they will iterate _only_ over those 12 cores that are allowed by the user'
s command line and in this example, will give 6 per socket. the other 6 per socket will be 'invisible' to the RM and thus the user can't create too many before int main.

**Comment by biddisco** [comment]
NB. The user could still iterate over those 12 cores and add them to several pools, and thus oversubscribe the cores, but only those ones that were declared by the command line. in this example 12 cores would be unused even if the user added the other 12 used ones to multiple pools and ended up creating 36 actual 'threads' on those 12 cores.

**Comment by biddisco** [comment]
or then again ....
if the resource_manager is created with an 'ignore_command_line' policy flag, then it could grab all the resources regardless of what was on the command line.

**Comment by biddisco** [comment]
Further discussion on resource managers/partitioners has brought up a new interesting twist.

Once we allow multiple thread pools, with different schedulers running on each pool, we will need to add an id_type for thread pools and corresponding decoration to remote async calls.

I may partition my system into a communication_pool, default_pool and a compute_pool - I wish to launch a task on a remote node, and have it run on the compute pool, or the communication_pool, rather than the default_pool. I will then with to get a handle (id_type) to the compute_pool on locality(x) and 
```
hpx::async( locality_id, compute_pool_id, action, args ...);
```

**Comment by hkaiser** [comment]
My understanding was that the `resource_partitioner` would sub-partition the machine before HPX was launched, thus leaving only a subset of the cores to HPX. The rest of the cores wouldn't be visible to HPX anymore.

If this understanding is incorrect, and we still want to expose those sub-partitions outside of the HPX domain to the user, we should use executors for this and not id_types.

**Comment by biddisco** [comment]
The plan was to allow multiple thread pools to be exposed to HPX on a single node.

On a local machine - there might be N thread pools. Each one has it's own scheduler and to launch a task on the mpi_pool, we would require
```
    auto mpi_pool = resource_manager.get_pool("mpi");
    auto mpi_executor = mpi_pool.get_executor();
    auto a_future = hpx::async(mpi_executor, stuff);
```
the purpose of this being to allow us to dedicate some cores to an mpi executor, some others to default pool and allow the user to create as many pools/schedulers as they require for their algorithmic needs.

But... supposing you want to launch a task on the mpi_executor of a remote node? Then it would be nice to have ID types for the different thread pools and be able to schedule a task to run on the remote node, on that pool. Either a remote executor ID, or a remote pool ID would be useful/required.

**Comment by hkaiser** [comment]
Yes, executors are the way to go, then.

**Comment by msimberg** [comment]
@biddisco @hkaiser Are there still API changes that you wish to see for the RP? If not, this can probably be closed (or more specific issues can be opened for whatever is missing).
