### ISSUE TITLE
Seg fault in  managed_component::get_base_gid,  possibly cause by  util::reinitializable_static 

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#2663]
I get a crash when running octo-tiger on supermic (compiled with gcc).
It is a seg fault in managed_component::get_base_gid, the output is here:
https://gist.github.com/neutrino504/6aee4c053de21d78a6b27a765c177b08

The problem went away when I modified "get_heap" (line 294) in hpx/runtime/components/server/managed_component_base.hpp by adding a lock so the body of get_heap is executed atomically. So it looks like there is a problem with util::reinitializable_static (which is used in get_heap).

**Comment by hkaiser** [comment]
Please show us the code you changed.

**Comment by dmarce1** [comment]
line 294 from  hpx/runtime/components/server/managed_component_base.hpp. I added the mutex and lock. 

static heap_type& get_heap()
            {
                // ensure thread-safe initialization
		static hpx::lcos::local::spinlock mtx;
		std::lock_guard<decltype(mtx)> lock(mtx);
                util::reinitializable_static<
                    heap_type, wrapper_heap_tag
                > heap(components::get_component_type<Component>());
                return heap.get();
            }

**Comment by hkaiser** [comment]
Frankly, I doubt it's a problem with `reinitializable_static` as this is using `call_once` internally for all synchronization. I rather thing this problem is caused by passing an rvalue to it's constructor which could have lead to a dangling reference inside some delayed initialization of the `reinitializable_static`. 

@dmarce1 Could you please try https://github.com/STEllAR-GROUP/hpx/tree/fixing_2663 to see whether that assumption is correct?

**Comment by dmarce1** [comment]
The problem appears to be fixed now.
