### ISSUE TITLE
One suspicion in parallel::detail::handle_exception.

### ISSUE THREAD

**Issue by taeguk** [STEllAR-GROUP/hpx#2834]
I have one doubt about parallel::detail::handle_exception.
https://github.com/STEllAR-GROUP/hpx/blob/76f7c3bc8eac51d73be7de4146b729335ce03c3f/hpx/parallel/exception_list.hpp#L26-L74
Above, the first ```handle_exception_impl<>::call()``` in Line 31 just throws exception. But, the second and third one return an exceptional future. As I think, this is strange. It seems inconsistent.

I think that the struct of Line 79 is for parallel algorithm called with ```execution::task```. So, in the struct, ```call()``` all both should return ```hpx::future<Result>```. (In other words, should return exceptional future.)
But in case of Line 27, it is different case. So, it should just return ```Result``` as I think. (In other words, should just throw exception.)

How do you think about this issue?

**Comment by hkaiser** [comment]
This looks suspicious, yes. I will try to investigate in more detail over the next days as I have no immediate answer to why we have it this way. Since all tests pass I'd suspect that 

- we either don't test all possible exceptional cases and the code is incorrect,
- the code in question above is never called,
- or simply the above code is correct

**Comment by hkaiser** [comment]
@taeguk has this been fixed by now?

**Comment by taeguk** [comment]
@hkaiser This has been not fixed by now. I thought that this is still suspicious. And I waited your reply until now.
How we go about this? Fixing this suspicious thing as I suggest? Or what should we do?

**Comment by hkaiser** [comment]
@taeguk I'd appreciate it for you to come up with a fix for this. Thanks!
