### ISSUE TITLE
multi node hello_world hangs

### ISSUE THREAD

**Issue by Dekken** [STEllAR-GROUP/hpx#2843]
Hi there,

I'm trying to setup a basic multi node example referencing [this](https://stackoverflow.com/questions/35367816/hpx-minimal-two-node-example-set-up) stackoverflow thread.

I've this setup
Master:
```
./bin/hello_world --hpx:localities=2 --hpx:agas=localhost:7910 --hpx:hpx=localhost:7910 --hpx:threads 4
```

Slave:
```
./bin/hello_world --hpx:agas=node0:7910 --hpx:hpx=localhost:7910 --hpx:worker
```

In strace, Master just hangs, while the slave seems to constantly be trying to connect.

It's probable I'm going about this wrong way, any input is appreciated

**Comment by hkaiser** [comment]
Please read the stack-overflow answer more carefully. The following should work:
```
./hello_world --hpx:localities=2 --hpx:agas=node0:7910 --hpx:hpx=node0:7910 --hpx:threads 4
./hello_world --hpx:agas=node0:7910 --hpx:hpx=node1:7910 --hpx:worker
```
(use the appropriate hostnames instead of `node0` and `node1`). If this does not work, try explicit IP-addresses instead of the hostnames.

The bottom line is that `node0` and `node1` should resolve to the correct IP address such that the two localities can communicate. If you use `localhost` this will always be resolved to `127.0.0.1` which makes sense in the context of a particular node only. HPX however sends the endpoint information you specify to locality zero where the `localhost` (which was meant to refer to `node1`) suddenly refers to `node0`, thus no connection can be established.

**Comment by Dekken** [comment]
I have tried both with localhost and actual (resolving) hostnames, both hang.

**Comment by Dekken** [comment]
IPs aren't working either.

Both devices are hot spotting from a phone, so I'll try setup a wired connection.

**Comment by hkaiser** [comment]
The reason for hanging can only be that the names you specify don't resolve to n IP address the other device can reach. The actual cause could be any of an endless list of possibilities, starting from firewall issues to a misconfigured DNS or simply not reachable IP addresses because of a missing route between the two endpoints. This is very difficult to diagnose from the distance.

**Comment by Dekken** [comment]
the devices were pingable (by name or IP) on the hot spot network, but it was interferrring somehow.

It works with a wired static network
