### ISSUE TITLE
Returning a future<R> where R is not default-constructable broken

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#2847]
@krivenko wrote (see #863):

Are return types of actions supposed to be default constructible?

Here is an extended version of `tests/unit/actions/return_future.cpp`

https://gist.github.com/krivenko/9e61c80e6adf4cd375af239f723dc752

`test_plain_call_future_non_default_ctor()` fails to compile with the following errors,
```
tuple.hpp:72:24: error: use of deleted function ‘non_default_ctor::non_default_ctor()’
```
```
base_lco_with_value.hpp:85:22: error: use of deleted function non_default_ctor::non_default_ctor()
```

**Comment by krivenko** [comment]
@hkaiser Thank you for opening this bug report for me, and for paying so much attention to these issues in general!

This is more of a 'good to have' feature, as far as I am concerned. I could certainly make my application work without the ability to pass non-default constructible types to and from actions, even tough this would result in more messy code.

Anyhow, would I have to implement anything besides `load_construct_data()` for my types, provided this issue is resolved? (Maybe #2846 is a better place to discuss this question...)

**Comment by hkaiser** [comment]
@krivenko: I think implementing `load_construct_data()` for your type should be sufficient.

**Comment by krivenko** [comment]
Perhaps a related issue...

If I delete the default constructor from my component (derived from `hpx::components::component_base`), I get the following error message

```
hpx/runtime/components/server/simple_component_base.hpp:304:64: error: no matching function for call to ‘mynamespace::my_component::my_component()’
             return static_cast<component_type*>(new Component()); //-V572
```

So, once again, can I avoid adding the default constructor?

**Comment by hkaiser** [comment]
@krivenko Hmmm, components shouldn't be required to be default constructible. It all depends on how you create them. So the following should be fine:

    struct component : component_base<component>
    {
        component() = delete;
        component(int) { ... }
        ...
    };

    void foo()
    {
        client<component> c = new_<component>(find_here(), 42);
    }

If this does not work, please file a separate ticket.
