### ISSUE TITLE
Add split_future for future<vector<T>>

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#2940]
For some reason this was left out when we implemented split_future in the first place :/

**Comment by hkaiser** [comment]
After looking into this a bit more I now understand why we have not implemented split_future for std::vector yet.

Please consider:

    std::vector<future<T>> split_future(future<std::vector<T>> && f);

in order for this to work efficiently we need to know how many elements are stored in the input vector without waiting for the future to become ready (as waiting for the future to become ready just for this would defeat the purpose). But have no way of knowing how many elements will be held by the vector before that.

What we could do is to implement:

    std::vector<future<T>> split_future(future<std::vector<T>> && f, std::size_t size);

(with 'size' specifying the number of elements the vector is expected to hold) as in some circumstances you know upfront how many elements to expect.

**Comment by biddisco** [comment]
I concur that it was omitted originally because the size was not known.

In the event that the user 'just happens' to know how many vectors elements to expect - would s/he not use a stds::array - which is supported. 

Are you trying to create work for yourself - or do you need a vector - in which case your solution appears fine. if the vector had >N elements, you could throw, and if less, then the remainder could be filled with ready futures - or something.

**Comment by spetruzza** [comment]
This worked for me. 
Thanks
