### ISSUE TITLE
Use of `std::rand` has UB risk in tests

### ISSUE THREAD

**Issue by zao** [STEllAR-GROUP/hpx#2954]
The range of `std::rand` varies per OS, and on some Linux CRTs `RAND_MAX` is very close to `INT_MAX`.

In `tests.unit.parallel.algorithms.partition` we grab a random value from a seeded `std::rand` and use it as the middle value in a range `[rand_base - half_range, rand_base + half_range]` for `test_partition => test_partition_heavy => random_fill`.

When the random value is large enough, we overflow the integer and end up constructing an `uniform_int_distribution<int>` with a lower bound larger than the upper bound. This is UB and results on a stack overflow on my Linux box.

https://github.com/STEllAR-GROUP/hpx/blob/84d0e982ec5289f4bccf3044b63f0cd55a376cf2/tests/unit/parallel/algorithms/partition_tests.hpp#L369
https://github.com/STEllAR-GROUP/hpx/blob/84d0e982ec5289f4bccf3044b63f0cd55a376cf2/tests/unit/parallel/algorithms/partition_tests.hpp#L87

There are something like 887 occurences of `std::rand` in HPX, most in tests and examples, but some in the library itself. We should probably audit them and consider replacing them with a separate PRNG like MT. This would also make tests more deterministic across implementations, and would isolate against external libraries invoking `rand` behind our backs.

**Comment by hkaiser** [comment]
@taeguk would you have time to look into this?

**Comment by taeguk** [comment]
@zao
Yes. you're right. I agree about your opinion. Using PRNG is better and recommended since c++11. I also think that we should replace ```std::rand```  to PRNG.

**Comment by Anushi1998** [comment]
I have tried to come up with replacing std::rand() with the inbuilt mt19937 generator.I have a [diff](https://patch-diff.githubusercontent.com/raw/Anushi1998/hpx/pull/1.diff) file changing some code in [data_copy.cu](https://github.com/STEllAR-GROUP/hpx/blob/master/examples/compute/cuda/data_copy.cu).I would like to know if I am proceeding in the right direction so that I can continue changing 208 more files ahead.
Any suggestions/criticism are most welcome :)

**Comment by hkaiser** [comment]
What's your rationale of using `std::chrono::high_resolution_clock` (instead of `std::time`) for generating the seed? I thought `std::random_device` was the 'proper' way of doing this nowadays.

Otherwise, sure - in order to use a standard random number generator you need to create an instance of and use it as a callable.

**Comment by Anushi1998** [comment]
@hkaiser Sorry, I was unaware of this seeding technique.I have now changed it to `std::random_device`.
I hope [this](https://patch-diff.githubusercontent.com/raw/Anushi1998/hpx/pull/1.diff) now looks better :)

**Comment by msimberg** [comment]
This is subjective, but maybe you could:
- use `gen` as a name for the generator instead of `_rand`?
- whenever possible use an explicit distribution (like in the example [here](http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution)) instead of using `x % n + y`?
