### ISSUE TITLE
segmented algorithm tests take too long to compile

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#3053]
Compilation of the segmented algorithm tests takes a very long time, uses too much memory and has caused nodes to fail when I use `make -j` by mistake.

We should make segmented algorithms (or just their tests) optional until such time as they can be made more user friendly.

**Comment by aserio** [comment]
@biddisco How long is a long time? I have been doing some thinking about this and I believe that we intend to develop more APIs on top of the segmented algorithms. Therefore, we should at least continue to make sure they are integrated properly into the library.

**Comment by sithhell** [comment]
Am 07.12.2017 11:54 nachm. schrieb "Adrian Serio" <notifications@github.com
>:

@biddisco <https://github.com/biddisco> How long is a long time? I have
been doing some thinking about this and I believe that we intend to develop
more APIs on top of the segmented algorithms. Therefore, we should at least
continue to make sure they are integrated properly into the library.


I don't have the raw numbers. But they don't only take a long time
(minutes) but also a ridiculous amount of memory (several gigabytes). The
compilation is severely broken in that regard.
Before you think about developing new algorithms on top of it, this needs
to be fixed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/STEllAR-GROUP/hpx/issues/3053#issuecomment-350119560>,
or mute the thread

**Comment by sithhell** [comment]
As a very rough point of measure, on circleci, the parallel unit tests take 1h8m to build. All the remaining ones take 34m. A significant amount of time is spent with building the segmented algorithms tests.

**Comment by aserio** [comment]
So we want to add a flag so that users can disable the parallel algorithm unit tests?
