### ISSUE TITLE
Serializing a GID Fails

### ISSUE THREAD

**Issue by aserio** [STEllAR-GROUP/hpx#3075]
I have come across an odd quirk while trying to checkpoint components. The test below should serialize the GID of the component, however, it fails with an exception. Naturally, checkpointing the GID is not my end goal, nevertheless, this test should still run and produce expected behavior:
```
#include <hpx/hpx_main.hpp>
#include <hpx/include/iostreams.hpp>
#include <hpx/dataflow.hpp>
#include <hpx/lcos/future.hpp>
#include <hpx/runtime/serialization/serialize.hpp>
#include <hpx/runtime/serialization/vector.hpp>
#include <hpx/util/checkpoint.hpp>
#include <hpx/include/components.hpp>

#include <cstddef>
#include <fstream>
#include <iosfwd>
#include <sstream>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

struct data_server
  : hpx::components::component_base<data_server> 
{
    data_server() = default;
    ~data_server() = default;

    data_server(std::vector<int> && data)
      : data_(std::move(data))
    {}

    void print()
    {
        for (int i=0; i<data_.size(); i++)
        {
            hpx::cout<<data_[i];
        }
        hpx::cout<<std::endl;
    }
    HPX_DEFINE_COMPONENT_ACTION(data_server, print, print_action);

    std::vector<int> data_;

    // Serialization Definition
    friend class hpx::serialization::access;
    template <typename Archive>
    void serialize(Archive& arch, const unsigned int version)
    {
        arch& data_;
    };
};
typedef hpx::components::component<data_server> data_server_type;
HPX_REGISTER_COMPONENT(data_server_type, data_server);

HPX_REGISTER_ACTION(data_server::print_action);

struct data_client
  : hpx::components::client_base<data_client, data_server> 
{
    typedef hpx::components::client_base<data_client, data_server> base_type;
    data_client() = default;
    ~data_client() = default;

    data_client(hpx::id_type where, std::vector<int> && data)
      : base_type(hpx::new_<data_server>(hpx::colocated(where), data))
    {}

    hpx::future<void> print()
    {
        data_server::print_action act;
        return hpx::async(act, get_id());
    }
};

int main()
{
    std::vector<int> vec{1,2,3,4,5};
    data_client A(hpx::find_here(), std::move(vec));
    A.print();

    hpx::future<hpx::util::checkpoint> f = hpx::util::save_checkpoint(A);
    f.get();
    hpx::cout<<"Hello World!"<<std::endl;
    return 0;
}
```

**Comment by sithhell** [comment]
Am 14.12.2017 5:34 nachm. schrieb "Adrian Serio" <notifications@github.com>:

I have come across an odd quirk while trying to checkpoint components. The
test below should serialize the GID of the component, however, it fails
with an exception. Naturally, checkpointing the GID is not my end goal,
nevertheless, this test should still run and produce expected behavior:

Obvious questions: what exception do you get?
What is the expected behavior? Should a checkpointed gid hold the component
alive?


#include <hpx/hpx_main.hpp>
#include <hpx/include/iostreams.hpp>
#include <hpx/dataflow.hpp>
#include <hpx/lcos/future.hpp>
#include <hpx/runtime/serialization/serialize.hpp>
#include <hpx/runtime/serialization/vector.hpp>
#include <hpx/util/checkpoint.hpp>
#include <hpx/include/components.hpp>

#include
#include
#include
#include
#include
#include <type_traits>
#include
#include

struct data_server
: hpx::components::component_base<data_server>
{
data_server() = default;
~data_server() = default;

data_server(std::vector<int> && data)
  : data_(std::move(data))
{}

void print()
{
    for (int i=0; i<data_.size(); i++)
    {
        hpx::cout<<data_[i];
    }
    hpx::cout<<std::endl;
}
HPX_DEFINE_COMPONENT_ACTION(data_server, print, print_action);

std::vector<int> data_;

// Serialization Definition
friend class hpx::serialization::access;
template <typename Archive>
void serialize(Archive& arch, const unsigned int version)
{
    arch& data_;
};

};
typedef hpx::components::component<data_server> data_server_type;
HPX_REGISTER_COMPONENT(data_server_type, data_server);

HPX_REGISTER_ACTION(data_server::print_action);

struct data_client
: hpx::components::client_base<data_client, data_server>
{
typedef hpx::components::client_base<data_client, data_server> base_type;
data_client() = default;
~data_client() = default;

data_client(hpx::id_type where, std::vector<int> && data)
  : base_type(hpx::new_<data_server>(hpx::colocated(where), data))
{}

hpx::future<void> print()
{
    data_server::print_action act;
    return hpx::async(act, get_id());
}

};

int main()
{
std::vector vec{1,2,3,4,5};
data_client A(hpx::find_here(), std::move(vec));
A.print();

hpx::future<hpx::util::checkpoint> f = hpx::util::save_checkpoint(A);
f.get();
hpx::cout<<"Hello World!"<<std::endl;
return 0;

}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/STEllAR-GROUP/hpx/issues/3075>, or mute the thread

**Comment by aserio** [comment]
Unhandled exception thrown: read access violation.
**std::_Tree_comp_alloc<std::_Tmap_traits<hpx::naming::gid_type const * __ptr64,hpx::naming::gid_type,std::less<hpx::naming::gid_type const * __ptr64>,std::allocator<std::pair<hpx::naming::gid_type const * __ptr64 const,hpx::naming::gid_type> >,0> >::_Myhead**(...) returned 0xFFFFFFFFFFFFFFFF. occurred

**Comment by sithhell** [comment]
Am 14.12.2017 6:23 nachm. schrieb "Adrian Serio" <notifications@github.com>:

Unhandled exception thrown: read access violation.
*std::_Tree_comp_alloc<std::_Tmap_traits<hpx::naming::gid_type const *
__ptr64,hpx::naming::gid_type,std::less<hpx::naming::gid_type const *
__ptr64>,std::allocator<std::pair<hpx::naming::gid_type const * __ptr64
const,hpx::naming::gid_type> >,0> >::_Myhead*(...) returned
0xFFFFFFFFFFFFFFFF. occurred


OK, makes sense. A debug build should give a meaningful assert as well.

The biggest question though is:
Does saving a gid to a checkpoint extends the lifetime of the component it
points to?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/STEllAR-GROUP/hpx/issues/3075#issuecomment-351779056>,
or mute the thread

**Comment by hkaiser** [comment]
I think we should not conflate the semantics of checkpointing an `id_type` with its functionality. Checkpointing a managed `id_type` should either 

- throw an exception (as one might argue it does not make sense to save just the id of some object without saving the object itself, and if you checkpoint the bject there is no need for saving its id as well)
- force the `id_type` to be unmanaged before passing it to the serialization

Checkpointing an unmanaged `id_type` should just save it to the stream.

The actual problem aserio is referring to is that currently a plainly initialized output_archive fails to serialize an instance of an `id_type` (if you view that instance as just another C++ type, i.e. stripped of its semantics in HPX).

**Comment by hkaiser** [comment]
> OK, makes sense. A debug build should give a meaningful assert as well.

It does, btw.

**Comment by sithhell** [comment]
Yes, I know why serializing and `id_type` fails. The bigger problem I see here is to mix up serialization (in terms of sending a parcel) and checkpointing to a file.
From the looks of it, those are two fundamentally different operations, semantically.
I would like to avoid to amend the serialization code with special cases needed for checkpointing. I don't have a solution at hand.
I guess the semantics with throwing an exception for managed ids can be implemented with a special container used during preprocessing.
