### ISSUE TITLE
HPX_SERIALIZATION_SPLIT_FREE does not stop compiler from looking for serialize() method

### ISSUE THREAD

**Issue by krivenko** [STEllAR-GROUP/hpx#3134]
I want to enable HPX serialization of a library type, whose definition I cannot change. For this purpose I define a pair of free functions `save()`/`load()` and make use of `HPX_SERIALIZATION_SPLIT_FREE`. Unfortunately, the type in question has a method called `serialize()`, which has nothing to do with HPX and it apparently gets into the way of name lookup.

```c++
#include <hpx/runtime/serialization/serialize.hpp>

struct has_serialize {
  int i;
  double d;

  void serialize() {
    // Does something unrelated to HPX serialization ...
  }
};

template <typename Archive>
void save(Archive &ar, has_serialize const &hs, const unsigned int) {
  std::cout << "saving" << std::endl;
}

template <typename Archive>
void load(Archive &ar, has_serialize &hs, const unsigned int) {
  std::cout << "loading" << std::endl;
}

HPX_SERIALIZATION_SPLIT_FREE(has_serialize);

int main() {

  has_serialize in, out;

  std::vector<char> buf;

  // Serialize
  hpx::serialization::output_archive oa(buf, hpx::serialization::disable_data_chunking);
  oa << in;

  // Deserialize
  hpx::serialization::input_archive ia(buf);
  ia >> out;

  return 0;
}
```
```
include/hpx/runtime/serialization/access.hpp:88:21: error: no matching function for call to ‘has_serialize::serialize(hpx::serialization::input_archive&, int)’
                     const_cast<typename util::decay<T>::type&>(
                     ^~~~~~~~~~
hpx_bug.cpp:7:8: note: candidate: void has_serialize::serialize()
   void serialize() {
        ^~~~~~~~~
hpx_bug.cpp:7:8: note:   candidate expects 0 arguments, 2 provided
```
This example compiles if I comment out `has_serialize::serialize()`.

`HPX_SERIALIZATION_SPLIT_FREE_TEMPLATE` seems to be affected too.

It's worth noting that Boost.Serialization does not suffer from this issue.

**Comment by hkaiser** [comment]
@AntonBikineev is that something you'd be interested/able to look into?

**Comment by AntonBikineev** [comment]
@hkaiser yes, I would

**Comment by AntonBikineev** [comment]
@hkaiser @krivenko 
I'm not sure that the folowing algorithm is documented. If it's not, I think it would be of use to do that.
To determine a way to serialize a user-defined type, the HPX serialization performs the following compile-time computations:
1) check if the type is non-intrusively polymorphic (using the trait `is_nonintrusive_polymorphic`) and if so, use `polymorphic_nonintrusive_factory` to serialize/deserialize the object;
2) otherwise, check if the type is intrusively polymorphic (i.e. has a member_function hpx_serialization_get_name) and if so, use `polymorphic_intrusive_factory` to serialize/deserialize the object;
3) otherwise, check if the type has a **serialize member-function with an arbitrary signature** and if so, use this member function;
4) otherwise, check if the type is `std::empty` and if so, do nothing;
5) otherwise, use unqualified lookup and ADL to find free functions with `serialize` name.

There are a couple of ways I can think of that may fix the problem:
1) we can provide another indirection layer and have, say, a metafunction `use_free_function<T>` that would be specialized inside `HPX_SERIALIZATION_SPLIT_FREE`. I don't like this because it complicates things and, moreover, doesn't solve the problem if you have a single free `serialize` function;
2) the better solution would be to constrain the check performed at the 3rd step to only consider function with the specific signature, e.g:
```
template <class T, class = void>
struct has_specific_serialize: std::false_type {};

template <class T>
struct has_specific_serialize<T, std::void_t<
        decltype(std::declval<T&>().serialize(
                std::declval<hpx::serialization::input_archive&>(), 0u))>>
: std::true_type {};
```
but I'm not sure that the minimal supported version of MSVS is good at dealing with expression-sfinaes...
@krivenko other than that, as a temporary solution, you can provide your own type on top the library type that would encapsulate/aggregate it.
@hkaiser @krivenko What are your thoughts on these ideas?

**Comment by hkaiser** [comment]
@AntonBikineev thanks for this analysis. I think going with what you suggested for (2) would be a viable solution. We can always find a way to detect a member function with a particular signature for MSVC, if the one you suggested makes it choke. But I'd assume this should be fine.

**Comment by sithhell** [comment]
Would it make sense to just swap 3) and 5)?

**Comment by krivenko** [comment]
@AntonBikineev Thank you for clarifying the serialization protocol!

I think it would actually be more important to explain it in the docs than to fix this particular issue.
Solution (2) looks reasonable to me. It would certainly fix the problem I am concerned with at the moment.

**Comment by AntonBikineev** [comment]
@sithhell why would we prefer free functions over member-functions? IMHO, member-functions are stronger tied to the type being serialized than free functions, e.g. a user might have a default templated fallback for the types that are standard layout or whatever:
```
namespace user_lib {
    template <class Ar, class T>
    void serialize(Ar& ar, T& t, unsigned) {
        std::memcpy or ....
    }
    struct dont_want_to_deal_with_serialization {
        int a;
        double d;
    };
    struct a_smarter_type {
        std::string s;
        template <class Ar>
        void serialize(Ar& ar, unsigned) {
            ar << s;
        }
    };
}
```

**Comment by hkaiser** [comment]
@AntonBikineev I'd say, please go ahead with (2)

**Comment by AntonBikineev** [comment]
@hkaiser,
Now I've run into another problem :)
Defining the trait (the second solution) doesn't work in our case, because the detection-idiom is subject to access checks that happen as a part of substitution process. This is why it doesn't work for the serialize method, which is often declared private.
Let's see what happens if we move this trait into the `hpx::serialization::access` class. According to the Standard:
> Declaring a class to be a friend implies that the names of private and protected members from the class granting friendship can be accessed in the base-specifiers and **member declarations** of the befriended class.

Given that the template argument in the template-id is part of a member-declaration, it appears to be valid, but gcc happens to reject this code (as opposed to clang). So now I'm trying to come up with a more portable solution...

**Comment by hkaiser** [comment]
@AntonBikineev fun!
