### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3263]
This issue is meant to collect feedback on the **content** our current documentation. For presentation see #3263.

The feedback I've received is that while the documentation is quite comprehensive, it's difficult to find specific things, and it's difficult to get started with the very basics (essentially just building and compiling a hello world, and some of the pitfalls related to async, continuations etc.).

I've started writing a short quick start guide, which should take a new user (on Linux) from getting HPX to hello world, to the basics of `hpx::async`/`hpx::parallel::` (not distributed), and giving them some hints on where to go next. This is focused on using HPX on a single node, but should still work well as a stepping stone for people who want to do distributed HPX. I will test this first at CSCS.

I'd like to hear both positive and negative experiences with the documentation. Whether you're a new or old user, I would like to ask you to comment below using the following templates (one comment per topic):

* I want to X with HPX (compile it, configure it, write hello world, write a very complicated component, debug it, etc.)
* I was (not) able to find documentation on it
* (if positive answer above) It was easy/difficult to find what I wanted
* Once I found what I wanted, the content was easy/difficult to understand

or

* I had difficulties with X (could not get my program to compile, my program did not work as expected) and could not find anything to help me in the documentation

Please also explain why you found something easy or difficult.

**Comment by msimberg** [comment]
#2589

**Comment by msimberg** [comment]
#2590

**Comment by bremerm31** [comment]
I difficulty learning how to write distributed HPX from the documentation. In my opinion the documentation is really good as a reference for looking up how to write distributed HPX code. However, I remember originally I had a lot of difficulties adopting the examples to fit my own application. In particular, I think a few issues I had:
- Things like stencil-8 are a bit too optimized for the purposes of demonstrating a simple example. I remember getting bogged down in the custom allocator stuff a lot in the beginning.
- Instead of having a set of application examples, I think it would have been preferable to have the tutorials name the concept they introduce, e.g. in this example we discuss futures, and in this example we discuss components and clients. I think I really needed @hkaiser to explicitly define all the formalism for me, and from there stuff became a lot more clear.
- It would be helpful to explicitly define concepts, and then make them linkable. Something like what's a client? Then anytime the term `client` is used later you can link to the definition. I think this would also help make clear that `client` is a special HPX concept.

Also, not sure if you're looking for formatting input, but I think the [deal.ii tutorial](http://www.dealii.org/8.5.0/doxygen/deal.II/Tutorial.html) is one of the nicest tutorials I have seen.

**Comment by msimberg** [comment]
@bremerm31 thank you, that's very useful feedback (and all input is appreciated)!

**Comment by msimberg** [comment]
I've uploaded a version of our documentation with slightly rearranged sections: [http://stellar.cct.lsu.edu/files/docs-playground/boostbook/html/index.html](http://stellar.cct.lsu.edu/files/docs-playground/boostbook/html/index.html).

So far the only new section is the quick start: [http://stellar.cct.lsu.edu/files/docs-playground/boostbook/html/hpx/applications.html](http://stellar.cct.lsu.edu/files/docs-playground/boostbook/html/hpx/applications.html) which is intended as an entry point and contains small tips and links to other sections of the manual. There is nothing *new* in there, but it collects the basics into one place.

The general idea is to group the documentation into higher level sections, and make the progression from building to single node parallelism to distributed to debugging clearer. There are now some empty sections that I'd still like to fill in:

- Troubleshooting (common mistakes)
- Debugging
- A higher level intro to components and actions (these could be added to the terminology section and linked to as @bremerm31 suggested; could also have a short intro under the distributed HPX section)

What do you think about this direction?

**Comment by bremerm31** [comment]
I'm a big fan of the terminology section. 

(Also: I think the link in the Accumulator example (3rd paragraph) to the Fibonacci example is currently just linking to the main documentation page).

**Comment by msimberg** [comment]
Good to hear. And the terminology section was there all along (not sure if you noticed?).

Yeah, links are most probably broken all over the place because of moving stuff around, so just patiently ignore that for now.

**Comment by msimberg** [comment]
I'm going to close this now since the sphinx documentation was merged. Feel free to comment here with thoughts about the new documentation though, or open a new issue if there's something bigger that you feel needs documenting/improvement.
