### ISSUE TITLE
CMake Targets for HPX

### ISSUE THREAD

**Issue by jayeshbadwaik** [STEllAR-GROUP/hpx#3408]
This is more of a question than an issue. Is it possible to use HPX with CMake with Targets? For example, can I do `target_link_libraries(mylib INTERFACE/PUBLIC/PRIVATE HPX::HPX)`? 

I've trying to search for this and could not find anything. So, if I'm missing something obvious, I'm sorry. Thanks.

**Comment by sithhell** [comment]
Hi @jayeshbadwaik, it is generally possible to use the `hpx` target (which refers to the main HPX library). However, you might not get everything that's need in addition (for example libhpx_init.a). The docs don't mention it for exactly this reason. It's generally not recommended.
In order to setup a CMake target, you should use `hpx_setup_target`, as documented here: https://stellar-group.github.io/hpx/docs/html/hpx/manual/build_system/using_hpx/using_hpx_cmake.html#hpx.manual.build_system.using_hpx.using_hpx_cmake.cmake_integrate_hpx

Does this solve your confusion?

**Comment by jayeshbadwaik** [comment]
Yes. Thank you. :-)
