### ISSUE TITLE
HPX library path

### ISSUE THREAD

**Issue by rtohid** [STEllAR-GROUP/hpx#3448]
HPX_LIBRARY_DIR holds paths to libraries that HPX depends on but not the path to HPX libraries.

**Comment by rtohid** [comment]
If you look into HPXConfig.cmake, the path to HPX libraries (libhpx(d).so, ...) is not included in HPX_LIBRARY_DIR.

**Comment by biddisco** [comment]
If the user's project uses `find_package(HPX)` ... then the HPXConfig.cmake sets the HPX libraries up as imported targets and the paths are known to cmake so there should not be any problem linking to HPX. 
I have dozens of projects using HPX and none of them have any problem finding the hpx libs.

**Comment by hkaiser** [comment]
@biddisco this works only if your dependent project relies on the exported targets to find the libraries. Unfortunately projects that do it the 'old cmake way', i.e. rely on `HPX_LIBRARY_DIR` and `HPX_LIBRARIES` will not be able to find the HPX libraries as none of those have the full path to `libhpx.so`.

**Comment by sithhell** [comment]
Could you please clarify what the actual problem is? Our cmake setup doesn't work anymore without imported targets. Even though the path to the library is not inside `HPX_LIBRARY_DIR`, both `hpx_add_executable` (and friends) as well as `hpx_setup_target` should just work.

**Comment by biddisco** [comment]
All you have to do is
```
find_package(HPX) 
target_link_libraries(mytarget hpx)
```
there just isn't any need for those HPX_LIBRARY_DIR things any more

**Comment by hkaiser** [comment]
@biddisco I know. However, we have no control over that part of their build system. 
Is it so hard to add the library directory to `HPX_LIBRARY_DIR`? Would that break anything?

**Comment by biddisco** [comment]
If someone is using CMake incorrectly, it's not our place to backfix our CMake to work with theirs. Can we not ask them to simply fix their cmake or present a simple example that doesn't work and maybe we can see if there's really a problem that needs addressing.

**Comment by sithhell** [comment]
I'm also having difficulties imagining a use case which is not supported by our current setup. An example would help to clarify the issue, and either serve as regression test or advice for users with similar problems.

**Comment by hkaiser** [comment]
@sithhell @biddisco I understand why you're arguing this way. But really - does it hurt anybody if we added the library directory to the variable?

**Comment by sithhell** [comment]
The real problem is still not clear. What happens when we decide to remove the variable all together? As John pointed out, it's not needed anyway (which should be independent of how you consume our target). So I'm asking one more time: what's the issue you are seeing and how would we reproduce it?
Why should we add anything without any value?

**Comment by sithhell** [comment]
That question doesn't help. Of course it won't hurt anyone. But why should we if it isn't needed to begin with? The variable can be considered obsolete. It doesn't serve a purpose. Of course, there is a reason why this issue has been opened in the first place, which is what I'm trying to figure out since two days ;)
