### ISSUE TITLE
Modernize CMake used in HPX

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#3474]
## Expected Behavior
Modern CMake thoughout

## Actual Behavior
The CMake commands
```
add_compile_options
include_directories
link_directories
link_libraries
```
are deprecated and should be replaced with  
```
target_compile_options
target_include_directories
target_link_libraries
```
This is mostly inspired by things I didn't like when implementing  #3458. we need a bit of a makeover in places.

**Comment by chinz07** [comment]
It might also be a good idea to use compile features (cxx_std_11, ...) instead of explicit flags to enable newer standards. This should reduce the probability for compatibility problems as CMake can choose a suitable version based on the requirements for all targets.

**Comment by biddisco** [comment]
Yes. The whole CMake setup needs a good cleaning up. The macros that appear throughout are awful as are as things like adding `_exe` extensions to targets which is terribly annoying. 
Are you volunteering?

**Comment by biddisco** [comment]
Regarding the CXX 11/14/17 - we do try to support different compilers and so it is nice to force a build to use C++11 or C++14 depending on what the user asks for (or the testing CI stuff), so we probably wouldn't wat to do away with it altogether. The problem is that we support new language features if they are available, and support older stuff f not, so allowing cmake to decide for us will prevent the old stuff being tested. If we can keep the old functionality, but clean things up, then great ...

**Comment by chinz07** [comment]
> Yes. The whole CMake setup needs a good cleaning up. The macros that appear throughout are awful as are as things like adding `_exe` extensions to targets which is terribly annoying.
> Are you volunteering @chinz07 ?

I would love to help with this issue. For me as a consumer, HPX's arcane build system is one of the major pain points. Incidentally, my project has a similar structure (runtime library + several (optional) backends). It might be possible to adapt some of the code patterns. I will review the current build system and compile a preliminary plan of action for the modernization. Afterwards, we can discuss how to include any corner case or additional constraints I might have missed. I think this is the most reasonable course of action.

> Regarding the CXX 11/14/17 - we do try to support different compilers and so it is nice to force a build to use C++11 or C++14 depending on what the user asks for (or the testing CI stuff), so we probably wouldn't wat to do away with it altogether. The problem is that we support new language features if they are available, and support older stuff f not, so allowing cmake to decide for us will prevent the old stuff being tested. If we can keep the old functionality, but clean things up, then great ...

If we would use compiler feature requirements, this would still be possible. Instead of mapping the HPX option (HPX_WITH_CXX0X, HPX_WITH_CXX11, ...) to the explicit compiler flag (-std=c++03, -std=c++11,..) one would use the corresponding requirement (none, cxx_std_11, ...). HPX would still be built using the selected standard.

While maintaining the same level of control, this change would make the consumption of HPX much simpler. For example, if I build my code using C++20 and HPX using C++17 CMake would currently add both -std=c++17 and -std=c++20 to the command line. Depending on the order of the flags the compilation might fail as my C++20 code might be compiled using C++17.

If one uses feature requirements, CMake will merge both (compatible) requirements into one flag "-std=c++20" avoiding this pitfall. In addition, one wouldn't need to maintain hard-coded flags for different compilers or compiler versions. 

Unfortunately, language standard requirements were only introduced as part of the CMake 3.8 release. This would require bumping the minimum version for CMake.

**Comment by chinz07** [comment]
Agreed! I am currently compiling a list of CMake features which might benefiting the modernization. Based on that information we can choose a suitable minimum version.

**Comment by chinz07** [comment]
After reviewing HPX's build system, I have compiled a preliminary outline for the modernization effort:

### Backward compatible changes

#### Remove the hpx_is_target macro

It is trivial and only used once.

#### Substituting most macros with functions

As functions introduce a separate variable scope they are much safer to use compared to macros.

This change is rather mechanical. A simple textual substitution macro -> function does only break a few macros. Most of these issues are trivial to fix except for the macros tying the parcelports into the runtime library. 

After the modernization, we might consider to remove some of the functions/macros. Removing all of them is not viable IMHO.

#### Removing the deprecated directory-based commands (add_compile_options, ...)

They should be replaced with the target-based variants (taget_compile_options, ...).

After removing the macros, this change should be costly but manageable.

#### Adding alias targets containing the 'hpx' namespace (e.g. hpx::hpx, hpx::hpx_init, ...)

Using namespaces does provide better error handling as CMake can distinguish between these targets and raw libraries.

#### Modernizing HPXConfig.cmake

* Populate the INTERFACE_INCLUDE_DIRECTORIES target property. "Linking" the targets should suffice to consume HPX. Ensure that HPX_LIBRARIES contains the HPX targets.

* Set HPX_INCLUDE_DIRS to "". The variable is now obsolete but has to be set to stay backward compatible.

* Clean-up HPX_LIBRARIES. Transitive dependencies should be specified via INTERFACE_LINK_LIBRARIES.

### Changes requiring CMake 3.8

#### Using compiler feature requirements (cxx_std_11, ...) instead of explicit standard flags

Different targets might set incompatible standard flags as usage requirements. If compiler feature requirements are used, CMake can merge the requirements into a single flag.

#### Reworking the integration of the parcelports

Afterwards we should be able to remove the remaining macros. 

Note: This might be partially possible with the current minimum version.

### Breaking changes

#### Adding the 'hpx' namespace to the exported target to provide better error handling

Accidentally linking a library (e.g. libhpx.so) directly is impossible after this change. Accidental linking might happen if a target without a namespace has not been properly defined and CMake tries to link against the corresponding library in /usr/lib/. As the directly linked library might be the wrong one, the resulting binary is usually subtly broken.

While this is a breaking change, adapting their code should be trivial for all users as they only need to switch to the new target names. If HPX_LIBRARIES is used to link against HPX, no changes are required.

### Further suggestions

#### Removing all variables from the cache which do not need to be persistent

Less state is always better.

#### Substituting all non-persistent global variables with global or target properties

Properties have a saner semantic compared to variables. Notably, properties can never accidentally shadow each other.

#### Reviewing the usage of cmake_policy

* Remove all obsolete cmake_policy(SET XXXX NEW) calls. cmake_minimum_required already sets most of them.

* Review all cmake_policy(SET XXXX OLD) calls and remove them after the issue has been fixed.

---

In general, I would like to split these changes into several PRs to make them easier to review and merge.

If you have any feedback or comments on this, please let me know.

**Comment by biddisco** [comment]
This would be great. We made a few changes this/last week and broke a few things (#3484 + friends), so any help would be very welcome. A complete clean up would be fabulous. If you start on this, please let us know so we can stay in the loop

**Comment by sithhell** [comment]
Thank you very much for the detailed explanation of the next steps. I'm in favor of all of them.

**Comment by chinz07** [comment]
I have submitted the first changes as PR #3514.

**Comment by hkaiser** [comment]
This can be closed as the build system has been thoroughly modernized over time.
