### ISSUE TITLE
Cmake version 3.5.1does not work (git ff26b35 2018-11-06)

### ISSUE THREAD

**Issue by Yeahhhh** [STEllAR-GROUP/hpx#3533]
##  Behavior

cmake failed

## Steps to Reproduce the Problem

cmake -DCMAKE_BUILD_TYPE={Release,Debug}     -DHPX_WITH_MALLOC=system  ..

-- Performing Test HPX_WITH_RDTSCP - pre-set to TRUE
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   atomic
--   filesystem
--   program_options
--   regex
--   system
-- WARNING: HPX will perform poorly without tcmalloc or jemalloc. See docs for more info.
-- Using system allocator.
-- GIT commit is ff26b352be146122ae8d02feb72230b99c55f2f4.
CMake Error at examples/resource_partitioner/CMakeLists.txt:14 (if):
  if given arguments:
    "CMAKE_CXX_COMPILER_VERSION" "VERSION_GREATER_EQUAL" "5.0"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "/home/aaa/hpx/hpx_git_x/bld/CMakeFiles/CMakeOutput.log".

## Specifications

... Please describe your environment

  - HPX Version:  git ff26b35 2018-11-06
  - Platform (compiler, OS):
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Ubuntu 16.04 x86-64
cmake version 3.5.1

**Comment by diehlpk** [comment]
VERSION_GREATER_EQUAL

I investigated and this command is only available at CMake 3.7+ and we should bump our minimal cmake version to 3.7. I will do a PR soon.

**Comment by hkaiser** [comment]
Couldn't we fix this without raising the cmake requirements?

**Comment by diehlpk** [comment]
Yes, we would need to add to all related files a check for the cmake version and depending on the version we would need the use the correct syntax. 

I checked and all major linux derivations have at least CMake 3.7, even debian stable has it. So I would recommend to upgrade the cmake version instead to add the check to all related files. 

@Yeahhhh Is using Ubuntu 16.04, which is around 2.5 years old and a little bit outdated.

**Comment by biddisco** [comment]
I am not interested in supporting very old compilers, or old cmake installations (it takes 5 minutes to build your own cmake on almost any machine). I suggest we bump the cmake requirement to 3.7 as suggested by @diehlpk

**Comment by chinz07** [comment]
I suggest that we should bump the CMake requirement to 3.8 instead. CMake 3.8 introduces the ability to require a specific language standard on a per target basis without manually specifying the (compiler-dependent) flag.

In my experience, HPX's handcrafted solution for selecting the requested standard and propagating this decision to downstream users is error-prone and hard to maintain. I would like to get rid of this particular part of the build system sooner rather than later.

**Comment by diehlpk** [comment]
@chinz07 Do you intend to submit these changes to the release 1.2? If yes, I would upgrade to 3.8, if not to 3.7 so people can build it on debian stable. Once you integrate this, we could upgrade to 3.8.

**Comment by hkaiser** [comment]
> I am not interested in supporting very old compilers, or old cmake installations (it takes 5 minutes to build your own cmake on almost any machine)

@biddisco you're the one advocating to reduce dependencies (in particular Boost linked libraries). Now you're suggesting to add another burden onto the user?

> Do you intend to submit these changes to the release 1.2?

@diehlpk, @chinz07 I don't think that adding such changes to the release is advisable. 

In general, I'd be fine with raising the cmake requirements to a reasonable version, I'd strongly suggest to do that after the release, though - possibly in relation with a redesign of our build system. For the release I'd suggest to find a different solution for the discussed problem.

**Comment by diehlpk** [comment]
@hkaiser The fix for the release will be a little bit messy because we would have to add to all CMake files an additional if case where we check for the cmake version. I could do this, but I do not think it is worth since all major Linux systems provide at least 3.7.

**Comment by hkaiser** [comment]
Why, just use `LESS` and `EQUAL` everywhere. No harm done.

**Comment by chinz07** [comment]
@diehlpk @hkaiser Just to clarify, I wanted to suggest to bump the requirement after the 1.2 release. I wrongly assumed that the proposed change would already target HPX 1.3.

VERSION_GREATER_EQUAL seems to be used only once. Am I missing something?

**Comment by diehlpk** [comment]
@chinz07 Ok, I will provide a PR soon and just update this one occurrence.

**Comment by sithhell** [comment]
Just to clarify, CMake 3.5 support `VERSION_LESS` and `VERSION_GREATER`. Those should be used at the place in question. `LESS_EQUAL` has slightly different semantics and should be avoided.

This should do the trick:
`NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 5.0`

**Comment by sithhell** [comment]
@Yeahhhh please try #3534 and see if it fixes your problem.

**Comment by Yeahhhh** [comment]
I switched to Ubuntu1804+cmake 3.10.2.

**Comment by biddisco** [comment]
> @biddisco you're the one advocating to reduce dependencies (in particular Boost linked libraries). Now you're suggesting to add another burden onto the user?

Any serious developer who wants to use HPX should be using a more recent compiler and toolchain. It's just not our business to support older technologies. The principle of open source is not that every user in the world is allowed to complain that X doesn't work on their system, it's there so that if they care enough to complain about it, they can take the 5 minutes to try to fix it. As it turns out, @sithhell cares enough, and he has supplied a patch. There are lots of places in HPX where I do care, and I do spend my time trying to help: I've spent a great deal of time trying to provide build system tools to help our coverage of problems on all PRs, but at some point, we must draw a line. Mine is just a tadge higher than yours in this case - and I do not feel bad about it (so don't try to make me feel guilty).

**Comment by biddisco** [comment]
On reflection. I do feel guilty. I should have taken the 5 minutes to change `greater_equal` to `not less` since it is so simple. And I checked and cmake 3.5 only dates back to 2016, which is not such a long time ago. So please accept my apologies for being grumpy about this.
