### ISSUE TITLE
Modularization of HPX

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#3546]
If we were to modularize HPX, what modules would we want? Please populate this list and move things around as appropriate

- Threading : Thread pools
- Schedulers : Does this need to be in threading?
- Runtime : affinity, resource managment
- Synchronization : futures, mutexes, lcos, etc
- Executors : 
- Parallel algorithms : The STL stuff
- AGAS : Anything that uses components
- Parcelport : Can this be independent of AGAS?
- Distributed (Partitioned Vector) STL type algorithms

**Comment by msimberg** [comment]
Thanks @biddisco for starting this list. Moved some things around. I would personally like to see the concept a full runtime as a layer on top of thread pools and schedulers since one might not always need the full machinery with config options etc. but instead just a simple thread pool.

I think the most important separation would be between local and distributed features which would give us a proper `HPX_WITH_NETWORKING=OFF` instead of what we have now which still requires many things that are not needed or can't be used with networking off.

**Comment by K-ballo** [comment]
> @K-ballo would you happen to have one of your header dependency graphs around?

Nothing even remotely recent. I'll try building a fresh one in the following days.

**Comment by K-ballo** [comment]
> > @K-ballo would you happen to have one of your header dependency graphs around?
> 
> Nothing even remotely recent. I'll try building a fresh one in the following days.

Here goes nothing... Attached as a [compressed SVG file](https://github.com/STEllAR-GROUP/hpx/files/2591401/headers.zip).

**Comment by msimberg** [comment]
Thanks @K-ballo, that's an interesting... mess.

**Comment by hkaiser** [comment]
I think we can close this as we have finished modularizing all of the HPX core code.
