### ISSUE TITLE
compatibility issue with pybind11

### ISSUE THREAD

**Issue by Jiazheng-Yuan** [STEllAR-GROUP/hpx#3569]
behavior:
error: 'run_as_hpx_thread' is not a member of 'hpx'
     hpx::run_as_hpx_thread(get);
          ^~~~~~~~~~~~~~~~~
and
error: 'run_as_hpx_thread' is not a member of 'hpx::thread'
     hpx::thread::run_as_hpx_thread(get);

I tried the hpx::future  with some basic python libraries through pybind11 such as numpy in it and it will crash. So i guess this is probably not compatible. Then I try to see whether the suggested hpx::thread::run_as_hpx_thread  would bring me some light. However, this is the output. 

code I use
```
#include<pybind11/embed.h>
#include <hpx/hpx_main.hpp>
#include <hpx/include/iostreams.hpp>
#include <hpx/include/lcos.hpp>
#include <hpx/include/parallel_generate.hpp>
#include <hpx/include/parallel_sort.hpp>
#include<hpx/hpx_start.hpp>
#include<pybind11/pybind11.h>
#include<iostream>
namespace py = pybind11;
void get(){
	std::cout<<"aaa"<<"\n";
}
int main(){
    hpx::thread::run_as_hpx_thread(get); 
    double root_two = math.attr("sqrt")(2.0).cast<double>();

    return 0;
}
```
I also tried to use hpx::run_as_hpx_thread() which is the format on the official document, doesn't work either. Did i miss anything? Thanks !

... Please describe your environment

  - HPX Version:1.2.0
  - Platform (compiler, OS):g++ (Debian 8.2.0-9) 8.2.0

**Comment by hkaiser** [comment]
You'll need either `hpx_main.hpp` or `hpx_start.hpp`, but not both (depending on how you want to launch HPX, see the docs for more details). For `hpx::thread::run_as_hpx_thread();` you'll need to `#include <hpx/runtime/threads/run_as_hpx_thread.hpp>` (see https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/threads/run_as_hpx_thread.hpp).

Otherwise, I will try to find some time today to look into your issue.

**Comment by msimberg** [comment]
@Jiazheng-Yuan please reopen if needed.
