### ISSUE TITLE
Trouble with using ranges-v3 and hpx::parallel::reduce

### ISSUE THREAD

**Issue by david8dixon** [STEllAR-GROUP/hpx#3641]
This may be more appropriate for stack overflow, but... I was hoping to get some advice on how to convince hpx that it is safe to apply a parallel reduction to a `ranges::view::transform` that unfortunately winds up with an input iterator category (see detail below). 

I tried this:
```c++
#include <boost/iterator/iterator_categories.hpp>  
namespace boost{
template<>
struct iterator_traversal<IterR>{
  using type = random_access_traversal_tag;
};
}
```
where IterR is:

```c++ 
using R = decltype(ranges::view::repeat_n(1.0,1000000000)
		   | ranges::view::transform(add_one) 
		   | ranges::view::bounded);

using IterR = decltype(R{}.begin())
``` 

## Expected Behavior

I would like to pass the result of `ranges::view::transform` to `hpx::parallel::reduce` and successfully compile/execute.

## Actual Behavior

Fails to compile because per Eric Niebler:

"By design. The old standard iterator categories require forward iterators to return real references. Your transform_range returns prvalues; hence, its iterator can model (C++98) InputIterator at best.

However, if you ask for ranges::iterator_category_t, you'll get the new-style iterator category, which is random-access."

https://github.com/ericniebler/range-v3/issues/961

Compiler output:
```
hpx/include/hpx/include/parallel_reduce.hpp:10:
hpx/include/hpx/parallel/algorithms/reduce.hpp:107:13: error: static_assert failed due to requirement 'hpx::traits::is_forward_iterator<basic_iterator<adaptor_cursor<basic_iterator<cursor>, adaptor<true> >
      > >::value' "Requires at least forward iterator."
            static_assert(
            ^
hpx/include/hpx/parallel/algorithms/reduce.hpp:275:24: note: in instantiation of function template specialization 'hpx::parallel::v1::detail::reduce_<const hpx::parallel::execution::sequenced_policy &,
      ranges::v3::basic_iterator<ranges::v3::adaptor_cursor<ranges::v3::basic_iterator<ranges::v3::repeat_n_view<double>::cursor>, ranges::v3::iter_transform_view<ranges::v3::repeat_n_view<double>,
      ranges::v3::indirected<(lambda at hpx_example/hpx_example.cpp:3:22)> >::adaptor<true> > >, double, std::__1::plus<double> >' requested here
        return detail::reduce_(
                       ^
hpx_example/hpx_example.cpp:44:32: note: in instantiation of function template specialization 'hpx::parallel::v1::reduce<const hpx::parallel::execution::sequenced_policy &,
      ranges::v3::basic_iterator<ranges::v3::adaptor_cursor<ranges::v3::basic_iterator<ranges::v3::repeat_n_view<double>::cursor>, ranges::v3::iter_transform_view<ranges::v3::repeat_n_view<double>,
      ranges::v3::indirected<(lambda at hpx_example/hpx_example.cpp:3:22)> >::adaptor<true> > >, double>' requested here
  auto result = hpx::parallel::reduce(hpx::parallel::execution::seq,
```

## Steps to Reproduce the Problem

https://wandbox.org/permlink/KcWne4bEQVJWdwNJ

## Specifications

... Please describe your environment

  - HPX Version: 3.3.2
  - Platform (compiler, OS): mac llvm 6.0.1

**Comment by hkaiser** [comment]
Looks like we need to teach our algorithms about the new iterator categories exposed by the Ranges TS. HPX decides about the category of a given iterator based on its own traits (see: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/traits/is_iterator.hpp). That also has some support for the Boost traversal categories (which apparently doesn't work as expected).

**Comment by david8dixon** [comment]
Thanks Hartmut. I look forward to seeing Ranges support in hpx!

**Comment by hkaiser** [comment]
@david8dixon Could you give me a minimal, self contained test case (beyond what's linked on wandbox above - that one does not rely on the Boost traversal tag).

Also, I'm afraid things are more complicated as our algorithms generally assume for the begin/end iterators to have the same type. That's another thing we'd need to fix.

**Comment by hkaiser** [comment]
The following code gives no compilation error:
```
#include <hpx/traits/is_iterator.hpp>
#include <boost/iterator/iterator_categories.hpp>

#include <iterator>
#include <numeric>

#include "range/v3/all.hpp"

double add_one(double d)
{
    return d + 1.0;
}

using R = decltype(
    ranges::view::repeat_n(1.0, 1000000000) |
    ranges::view::transform(add_one) |
    ranges::view::bounded);

using IterR = decltype(R{}.begin());

namespace boost
{
    template <>
    struct iterator_traversal<IterR>
    {
        using type = random_access_traversal_tag;
    };
}

static_assert((hpx::traits::is_forward_iterator<IterR>::value),
    "Requires at least forward iterator.");

int main() {}
```
So I'm not sure why you're seeing the error above.

**Comment by apmccartney** [comment]
Hello Harmut!

You are correct that the example in question compiles and is working as intended, but demonstrates two work arounds we hope to do away with when rebasing on some future version of HPX.

+ `ranges::view::bounded` provides a means to satisfying the homogeneous Iterator/Sentinel requirements of HPX's current algorithms. This is (imo) a reasonable client-side work around for the time being, especially given the tremendous value HPX brings to our work, but is easy to forget (leading to difficult to interpret compiler errors) and introduces a performance hit (albeit very likely small in practice).

+ The deduced iterator type `IterR` is defined to satisfy random_access_traversal by way of explicit specialization of the `boost::iterator_traversal` type trait. While this solution works, it requires a specialization for each Iterator of interest within the Boost namespace, which can prove difficult given the 
    + almost ad-hoc composition of range views in function scopes
    + idiomatic use of anonymous functions objects in these sorts of higher order functions

Unfortunately, the `boost::iterator_traversal_category` [implementation](https://www.boost.org/doc/libs/1_69_0/boost/iterator/iterator_categories.hpp) in written in such a way that providing a generic client-side adaption doesn't seem to be possible.

That said, I believe the [`is_forward_iterator`](https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/traits/is_iterator.hpp#L130) (and stronger) traversal category type_traits in HPX could be written in terms of SFINAE concept emulation to support this use case without introducing a dependence upon range-v3.

Would a pull request providing such an implementation be welcome?

-----

Just to review, should you (or anyone else following/reviewing this issue) not be familar with ranges-v3 and/or the ranges proposal:

+ `ranges::view::repeat_n` accepts two arguments `v` and `n` and returns a lazy range of identical elements equal to `v` with exactly `n` elements. 
  + The type returned by the resulting range's `begin` method (i.e the Iterator) is distinct from the type returned by the range's `end` method (i.e. the Sentinel).
  + The Iterator does model a random access iterator by the 98 standard definition, including the requirement that the indirection operator should return a reference to the reference element of the range.

+ `ranges::view::transform` accepts two arguments `r` and `t` and returns a lazy range of values resulting from applying `t`, an argument function object, to the elements of `r`, a range argument.
  + `ranges::view::transform` is 'pipeable', meaning that when a `transform` invocation appears on the right side of a binary or (or pipe) operator `|`, the argument on right of the pipe will be (effectively) substituted as the `r` argument.
  + `ranges::view::transform` preserves the homogeneity/heterogeneity of the source ranges Iterator and Sentinel types.
  +  `ranges::view::transform` preserves the traversal category of the source range as defined in concept (if not in code) [as defined](https://www.boost.org/doc/libs/1_69_0/libs/iterator/doc/new-iter-concepts.html) by the boost iterator library.

+ `ranges::view::bounded` accepts a range argument `r` with distinct Iterator and Sentinel types and returns a view of `r`, such that the Iterator and Sentinel types of the resulting view are the same.
  + `ranges::view::bounded` is 'pipeable', meaning that when a `bounded` appears on the right side of a binary or (or pipe) operator |, the argument on right of the pipe will be (effectively) substituted as the `r` argument.
  + The Iterator/Sentinel adaption does imply some performance degradation due to lost optimization opportunities, but is invaluable for working with traditional Iterator-based algorithms

---

**Comment by hkaiser** [comment]
@apmccartney Thanks for the extensive clarification. You were asking:

> Would a pull request providing such an implementation be welcome?

Absolutely! That would be very much appreciated.

Also, FWIW, I just created a ticket for us to adopt the iterator/sentinel model for all of our algorithms (see #3646). That shouldn't be difficult, it's just a lot of work.

**Comment by hkaiser** [comment]
@apmccartney Thanks for the test case. Let's make this work - I will fix `reduce` and you can provide us with the PR for the `is_..._iterator` traits.

**Comment by hkaiser** [comment]
@apmccartney I have now modified `reduce` to support iterator/sentinel pairs (see #3650)

**Comment by apmccartney** [comment]
I hope to have a pull request posted before the end of the day for review.

**Comment by hkaiser** [comment]
@apmccartney any news? can we help somehow?

**Comment by apmccartney** [comment]
I apologize for the delay. I was planning to complete this work during a conference, but the proceedings turned out to require more attention than I'd anticipated. I've started work on the described functionality this afternoon and anticipate have a pull request posted by tomorrow evening.

**Comment by hkaiser** [comment]
@apmccartney Sorry if I made the impression to try rushing you. I just wanted to make sure you have the support you might need. Thanks for working on this!
