### ISSUE TITLE
Transitive HPX target

### ISSUE THREAD

**Issue by jjwilke** [STEllAR-GROUP/hpx#3818]
Instead of exporting HPX_LIBRARIES and HPX_INCLUDE_DIRS, consider having target hpx transitively include these. This would more closely follow "modern cmake" where I just:

````
find_package(HPX)
target_link_libraries(target hpx)
````
and I'm done.

**Comment by msimberg** [comment]
This is long overdue and would be very nice to have. It would allow us to get rid of the special `add_hpx_executable` as well.

**Comment by msimberg** [comment]
By the way, if anyone feels like doing this: we actually already do provide targets, they just don't work correctly. In particular, they seem to be missing include directories (probably something else as well). But this would probably not be as tough to do as I imagined at first.

**Comment by msimberg** [comment]
#4028 will get us most of the way there. Some more fixing and testing will likely be required but most of the work will be there to make this work.

**Comment by aurianer** [comment]
On it !

**Comment by msimberg** [comment]
This is effectively possible right now, but I'd ask anyone itching for this to not rely on the current targets just yet. For libraries one can link to the `hpx` target and for applications one can link to `hpx_init hpx_wrap` and things should just work. For components one needs to manually set a few compile definitions which would normally be taken care of by the setup macros (`hpx_setup_target`).

While we'll probably keep the `hpx`, `hpx_init` and `hpx_wrap` targets around we should still do some bikeshedding on the targets. Presumably we'd want to namespace all public targets with `HPX::` (note, all caps as in the package name). We already have two helper targets `hpx::application` and `hpx::component` for dealing with pkgconfig but we'd likely want something similar for CMake users.

* `HPX::hpx` for libraries: no magic, just the base library
* `HPX::executable`: links with `hpx`, `hpx_wrap`, and `hpx_init` (executable, and not application, because of `add_executable`). Alternatively, merge `hpx_init` into `hpx` and require explicit linking with `hpx_wrap`/`HPX::wrap_main` when using the `hpx_main/main` wrapping magic. This way executables can also just link to `HPX::hpx` unless they want the extra magic.
* `HPX::component`: is anyone aware of a way to do e.g. `target_compile_definitions(mytarget HPX_APPLICATION_NAME=mytarget)` but with a target, i.e. `target_link_libraries(mytarget magic_target_that_can_introspect_mytarget)`?
* `HPX::plugin`: same as above but for plugins

The two last targets are the big question mark. If we can't do that we'll have to settle for keeping the macros for those use cases, or make it very clear somewhere in the documentation which compile definitions need to be set manually.

**Comment by msimberg** [comment]
Now that #4246 is merged into master, this is hopefully fixed. Please give it a try and let us know about any issues. Details about the targets are in #4246 and soon in the documentation (short story: link to `HPX::hpx`).
