### ISSUE TITLE
CMake all-keyword or all-plain for target_link_libraries

### ISSUE THREAD

**Issue by parsa** [STEllAR-GROUP/hpx#3857]
## Expected Behavior

For the following scenario to work:
```cmake
cmake_minimum_required(VERSION 3.12)

project(app1 CXX)

find_package(HPX REQUIRED)
find_package(Boost REQUIRED)

add_executable(app1 prog.cpp)
hpx_setup_target(app1)
target_link_libraries(app1 PRIVATE Boost::boost)
```
```cpp
int main()
{
    return 0;
}
```

## Actual Behavior

```
CMake Error at CMakeLists.txt:10 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "app1".  All uses of target_link_libraries with a target must be
  either all-keyword or all-plain.

  The uses of the plain signature are here:

   * C:/Repos/hpx/cmake/HPX_SetupTarget.cmake:218 (target_link_libraries)
```

## Steps to Reproduce the Problem

  1. cmake -H. -Bcmake-build-debug -G"Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE="C:/Repos/vcpkg/scripts/buildsystems/vcpkg.cmake" -DHPX_DIR="C:/Repos/hpx/cmake-build-debug/lib/cmake/HPX"
  1. cmake --build cmake-build-debug

## Specifications

  - CMake 3.12.4
  - HPX Version: 21e1131bea9f46aae1d4b38040cddfcee56b4568
  - Platform (compiler, OS): VS2017 (MSVC 19.16.27030.1)

**Comment by msimberg** [comment]
I think the long term solution is #3408. Until then the problem is that `HPX_TLL_PUBLIC` isn't set in `HPX_SetupTarget.cmake` when used from the install directory (it's only set in the build directory). Since we don't set those variables conditionally anymore I think we can use `PUBLIC` and `PRIVATE` directly (also see discussion in https://github.com/STEllAR-GROUP/hpx/pull/3828/files). At least users have the choice of using `PUBLIC` or `PRIVATE`, with the tiny downside that they can't use the plain version of `target_link_libraries` instead. How does that sound @parsa?

**Comment by parsa** [comment]
It's not a downside anymore. Sounds good.
