### ISSUE TITLE
/statistics/average@ perf counter can't be created

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#3958]
## Expected Behavior
An average value?

## Actual Behavior
```
bin/hello_world_1 --hpx:print-counter-interval=250 --hpx:list-counters --hpx:print-counter=/threads{locality#0/pool#*/total}/idle-rate --hpx:print-counter=/statistics/average@/threads{locality#0/pool#*/total}/idle-rate
```
```
{what}: couldn't create performance counter: /statistics{locality#0/total}/average@/threads{locality#0/pool#*/total}/idle-rate (invalid aggregate counter name (instance name must be valid base counter name): HPX(bad_parameter)): HPX(bad_parameter)
```

Am I doing it wrong?

**Comment by hkaiser** [comment]
Do you have the idle-rate counter enabled?

**Comment by biddisco** [comment]
yes. The idle rates are printed when I just ask for normal output, it only crashes when I add the /statistics/average@ prefix

**Comment by hkaiser** [comment]
@biddisco ok, try this instead: 
```
--hpx:print-counter=/statistics{/threads{locality#0/pool#*/total}/idle-rate}/average@<interval>
```
where `<interval>` is a number (in ms) that determines how often the underlying counter is queries in order to calculate the average.

(see also here: http://stellar.cct.lsu.edu/files/hpx-1.1.0/html/hpx/manual/performance_counters/names.html#hpx.manual.performance_counters.names.example for more examples, for instance, I'm linking the old docs as the sphinx docs don't have any ancors for the captions - btw @msimberg is that something that could be added?)

**Comment by msimberg** [comment]
@hkaiser FYI, this is the link to the same section in the sphinx docs: https://stellar-group.github.io/hpx/docs/sphinx/branches/master/html/manual/optimizing_hpx_applications.html#two-simple-examples. The difference is that you can't get it by clicking on the heading. When you hover close to the heading a little chain icon shows up that you can click to get the link to that heading. You can also get the link from the table of contents in the sidebar.

**Comment by hkaiser** [comment]
@msimberg ahh, nice to know, thanks!

**Comment by biddisco** [comment]
Thanks. The

**Comment by biddisco** [comment]
Thanks, the alternative counter name use seems to work. I must have been looking at old docs. Not sure. Should we make some doc changes?

**Comment by hkaiser** [comment]
Closing this a 'won't fix' as everything seems to work as documented.
