### ISSUE TITLE
CMake Error when '-DHPX_WITH_HPXMP=ON'

### ISSUE THREAD

**Issue by tianyi93** [STEllAR-GROUP/hpx#4134]
## Expected Behavior

CMake  build succeed

## Actual Behavior

cmake build errors

`CMake Error at cmake/HPX_SetupTarget.cmake:226 (target_link_libraries):
  Target "atomic" of type EXECUTABLE may not be linked into another target.
  One may link only to INTERFACE, OBJECT, STATIC or SHARED libraries, or to
  executables with the ENABLE_EXPORTS property set.
Call Stack (most recent call first):
  cmake/HPX_AddExecutable.cmake:166 (hpx_setup_target)
  libs/algorithms/tests/unit/algorithms/CMakeLists.txt:146 (add_hpx_executable)`
## Steps to Reproduce the `Problem`

... Please be as specific as possible while describing how to reproduce your problem.

set -DHPX_WITH_HPXMP=ON when build HPX

## Specifications

... Please describe your environment

  - HPX Version:10b514320953b5c67dac139b44b6a729edac76ec.
  - Platform (compiler, OS): ubuntu

**Comment by msimberg** [comment]
@tianyi93 this happens because in hpxMP there is a test (executable) named `atomic` (`tests/openmp/unit`), and HPX (at least in some cases) wants to link to `libatomic`. I think best would be if you could either rename the test or add a suffix to all your tests. In HPX we add a `_test` suffix to all tests to make it obvious that they are tests. Do you think something like that could be done in hpxMP?

**Comment by tianyi93** [comment]
@msimberg Thanks, the way you proposed did solve the CMake problem.
