### ISSUE TITLE
Consider using #pragma once

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4194]
This is a small convenience issue. Every now and then it happens that you want to create a new header file but start off by copying an existing header. Then you forget to update the include guards and spend far too long wondering why your definitions in the new header file aren't actually being defined. `#pragma once` would avoid this problem.

It's not standard but practically supported on every platform that we try to support. Is anyone wildly against this? Would this make someone's life a lot better? Don't care?

**Comment by hkaiser** [comment]
@msimberg the only comment I'd have is that I would like to have this used either consistently across the whole library or not at all. Otherwise I am mostly impartial on how we make sure that #includes are protected from multiple inclusion. Not sure if it is worth the effort to redo every header we have...

**Comment by K-ballo** [comment]
Weakly against.

**Comment by aurianer** [comment]
I'm slightly in favour since we could use the clang-format option `IndentPPDirectives` to obtain :
```
#ifndef VAR
#    define VAR
#    ifndef SUBVAR
#        define SUBVAR
#    endif
#endif
```
which is more readable, instead of :
```
#ifndef VAR
#define VAR
#ifndef SUBVAR
#define SUBVAR
#endif
#endif
```
The current problem is that using this clang-format option is indenting all the includes at the beginning of the file, considering the main `#if !defined(HPX_LCOS_FUTURE_MAR_06_2012_1059AM)`of the header, which is pretty ugly

**Comment by hkaiser** [comment]
From what I read, clang-format should properly ignore include guards: https://reviews.llvm.org/D35955. Does it not? They might just accept `#ifndef GUARD`, but not `#if !defined(GUARD)` - but that should be easily fixable, I think (some regex anyone?)

**Comment by aurianer** [comment]
True ! I'll do that then !
