### ISSUE TITLE
HPX freezes up with multiple new_ calls in a simple test program

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#4369]
The simple test program, available here:
https://github.com/dmarce1/new_test
when given the argument "4", should allocate 4096 bare bones components across 4 nodes. It freezes up when attempting to to this on queenbee. When running the same program with argument "3", it successfully allocates 512 components in less than a second and exits.

## Steps to Reproduce the Problem
Run the test program available here:
https://github.com/dmarce1/new_test
on 4 nodes of queenbee with argument 4.

## Specifications

... Please describe your environment

HPX commit 258bf04aae03c6864e06a0fad0f5c5848310a300
GCC 8.3 
queenbee2

**Comment by hkaiser** [comment]
This freeze is caused by a bad interaction between 'magic statics' (i.e. function local static variables) that require kernel-based locking and HPX threading, which does not interact well with kernel-based locking. The 'magic static' variable (https://github.com/dmarce1/new_test/blob/master/src/main.cpp#L10) causes for the kernel thread that is run by the HPX scheduler to block on initialization waiting for the right hand side to finish executing (which causes all HPX operations on the executing kernel-thread to be suspended). However in order to perform the right hand side (the `hpx::find_all_localities()`) requires HPX some functionality to be executed. So this runs into a difficult to understand deadlock situation. The solution for this is not to assign the result of `hpx::find_all_localities()` to a function local static.

Additionally: is there a reason the example you provided executes `hpx::new_().get()` in a new HPX thread created by `hpx::async`? I would assume that the code you provided is just a simplification of the real code that exposes the problem. In any case, for the example, there is no need to call `hpx::async([]() { return hpx::new_<tree>().get(); });`, as simple `hpx::new_<>()` would have done the trick here.

**Comment by dmarce1** [comment]
Hartmut-
I found that enclosing hpx::new_().get() in a future resulted in faster regridding with Octo-Tiger, the theory being that hpx::new_ doesn't return as quickly as hpx::async. Is this not true?

**Comment by hkaiser** [comment]
> I found that enclosing hpx::new_().get() in a future resulted in faster regridding with Octo-Tiger, the theory being that hpx::new_ doesn't return as quickly as hpx::async. Is this not true?

Interesting! But it makes sense. There is no need to call `new_<>().get()` however, as the embedded future should automatically get unwrapped.
