### ISSUE TITLE
Accessing the number of idle cores at runtime

### ISSUE THREAD

**Issue by scheherzade** [STEllAR-GROUP/hpx#4599]
## Expected Behavior

Could we have a function to determine the number of idle cores at runtime? I would like to make decisions within a custom parallel executor based on the number of idle cores.

**Comment by msimberg** [comment]
This is certainly doable. Would you only need to know how many threads are idle or also which threads are idle? Just keeping track of the number of idle threads with an atomic counter would likely be close to zero overhead (assuming threads go rarely from idle to busy and vice versa).

**Comment by biddisco** [comment]
Might not work well in many cases ... If a core becomes idle, it will steal work from another core (in general), so what you'll see is `NO cores idle ... NO cores idle ... NO cores idle ... ALL cores idle` - unless the tasks are long running and there are only a few of them - so that a few cores are busy for a substantial amount of time, with no stealing going on.

**Comment by hkaiser** [comment]
> This is certainly doable. Would you only need to know how many threads are idle or also which threads are idle? Just keeping track of the number of idle threads with an atomic counter would likely be close to zero overhead (assuming threads go rarely from idle to busy and vice versa).

We already have the counter that keeps track of idle cores (for the utilization perf-counter). We just would need to expose that.

**Comment by scheherzade** [comment]
@msimberg I just need to know the number of idle threads at the time I want to make a decision.

**Comment by hkaiser** [comment]
@scheherzade I think I know how to expose this value and will work on it asap.
