### ISSUE TITLE
References in the documentation

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#4698]
I have seen for other projects, that they provide some references in their documentation. For HPX, I think we should provide some references on the module page. For example, we could provide the references there, how people could cite the module. 

@msimberg Can we use BibTeX in our documentation to do so?

**Comment by msimberg** [comment]
I think we can (it may require a sphinx extension, but there are plenty of those). I'm not sure why exactly people should cite modules (these are small parts of HPX, mostly for our benefit rather than users' benefit). Do you essentially want to add something like the zenodo doi link to the documentation (except that it would be for the JOSS paper and maybe just a bibtex snippet that people can copy and paste)? This is not about referring to other works in our documentation, correct?

**Comment by diehlpk** [comment]
I was thinking that for example for the parcelport module, we could provide references to the parcelport providers. Same for the performance counters. 

I would say that both parties have a benefit. People could read/cite the publications related to the module, and we get citations.

**Comment by godslayer201** [comment]
Hello @msimberg @diehlpk,

I would like to take this up. I have worked with rtd and sphinx prior, and would be good exercise prior GSoD.

**Comment by diehlpk** [comment]
Hey @godslayer201 sounds good. Please let us know if you need more details?

**Comment by godslayer201** [comment]
Hello @diehlpk thank you for the reply. 

I've performed the local set-up for the docs and I'm currently reading through hpx's codebase and prior documentation to look at starting pointers. 

Will ping here or on IRC about my updates.
