### ISSUE TITLE
bug: "Assertion 'this == coroutine_.get_thread_id().get()' failed: HPX(assertion_failure)"

### ISSUE THREAD

**Issue by albestro** [STEllAR-GROUP/hpx#4800]
## Expected Behavior

Our [DLA-Future](https://github.com/eth-cscs/DLA-Future) library is built on HPX. Our CI/CD was not and it is still not reporting any issue with HPX 1.4.1.

On branch [`alby/porting_hpx1.5.0`](https://github.com/eth-cscs/DLA-Future/tree/alby/porting_hpx1.5.0) I'm working on porting to the new HPX API available on master, and since on this branch I'm not changing anything which is not strictly related to the HPX required changes, I expected it to pass the tests too.

## Actual Behavior

Unfortunately, on the branch [`alby/porting_hpx1.5.0`](https://github.com/eth-cscs/DLA-Future/tree/alby/porting_hpx1.5.0) not all tests are successful.

I see the same problem on different tests, but it seems more frequently and easily reproducible with `test_triangular`.

With a debug build, an extract of the [full report](https://github.com/STEllAR-GROUP/hpx/files/4864977/error-output.txt) is 
```bash
{file}: /Users/ialberto/workspace/libraries/hpx/libs/threading_base/include/hpx/threading_base/thread_data_stackful.hpp
{line}: 64
{function}: coroutine_type::result_type hpx::threads::thread_data_stackful::call(hpx::execution_base::this_thread::detail::agent_storage *)
{what}: Assertion 'this == coroutine_.get_thread_id().get()' failed: HPX(assertion_failure)
```

## Steps to Reproduce the Problem

Unfortunately, I was not able to narrow down the problem to a minimal reproducible problem.

I asked support to @biddisco about this (thanks a lot!), who was able to install all the dependencies of our library and replicate the problem (we patched `test_triangular` to make it easier to debug with a single MPI rank [patch-single-rank.txt](https://github.com/STEllAR-GROUP/hpx/files/4864981/patch-single-rank.txt)).

In case of need, I'm willing to support you installing our library.

## Specifications

  - HPX Version: `master`
  - Platform (compiler, OS): not specific to any platform (both on Linux and MacOS, respectively with GCC and apple-clang)

**Comment by biddisco** [comment]
Thanks @albestro  - looking at it now.

**Comment by biddisco** [comment]
I might need some help debugging this.

In the following trace, produced by some debug printf's I can see when the problem is happening (but not yet where)
on line 505, it can be seen that a task is scheduled inside the scheduling loop and becomes active, on line 506, the thread id `0x7f0b34091a70` appears at the start of the printf until line 509, where it returns control to the scheduling loop (appearing on line 511). Notice that the thread state is returned from task execution as `pending` - but on line 510 the thread_id `reset` is called on the coroutine and the coroutine thread id on line 511 is `0` (instead if `0x7f0b34091a70` again). I don't show it in this trace, but trust me, all threads that have their coroutine thread_id reset normally return their state as `terminated` and if they return with `pending` then the id is not reset. I am not sure when tasks can return with a `pending` state, but I presume something like a `yield_while` might do such a thing.

So either
1) a task is terminated, but is mistakenly returning a state of pending, or
2) a task yields/suspends, but has it's coroutine reset by mistake.
I can confirm that running with `hpx:threads=1` makes the problem go away, so it must be a race condition, but I cannot find the right piece of code to annotate, so that I can establish witch of the above hypotheses is correct. I suspect @sithhell or @hkaiser would be able to point me at the right place in the code to see where a task might exit the coroutine call and not be terminated. (I mean for example, here https://github.com/STEllAR-GROUP/hpx/blob/64244bff9af3f1f23f6ace4f67ca423d42ed3797/libs/coroutines/src/detail/coroutine_impl.cpp#L67-L90 a task returns from the coroutine and terminates, reset is called and things seem ok, but I cannot find where a task can exit from the coroutine and be still in a pending state - if I can locate that code - then I might be able to annotate it to see if something is fishy).

Any suggestions of things to look for gratefully received. Note that I cannot debug this interactively, since the fault is very random and the more debug statements I add, the less likely the race is to occur. Breakpoints are useless as we must run through thousands of tasks to find the one that fails.
 
```
500 <DEB> 0001978574 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     QH_THRD next_thread_NP       D 00 Q 002 TM 059 [BP n 000 w 000] [HP n 000 w 000] [NP n 000 w 000] [LP n 000 w 000] T     058 0x7f0b34091a70 0x7f0b34091a70 "hpx_main" thread_priority_normal  
501 <DEB> 0001978584 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     QH_NUMA get_next             D 00 Q 002 Qidx 002 taken D 00 Q 002 TM 059 [BP n 000 w 000] [HP n 000 w 000] [NP n 000     w 000] [LP n 000 w 000] T 058 0x7f0b34091a70 0x7f0b34091a70 "hpx_main"
502 <DEB> 0001978603 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     SCHLOOP old state            thread 0x7f0b34091a70 0x7f0b34091a70 "hpx_main" state pending
503 <DEB> 0001978610 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     SCHLOOP state 2              thread 0x7f0b34091a70 0x7f0b34091a70 "hpx_main" state active
504 <DEB> 0001978616 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     SCHLOOP state 3              thread 0x7f0b34091a70 0x7f0b34091a70 "hpx_main" state active
505 <DEB> 0001978623 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     SCHLOOP state 4              thread 0x7f0b34091a70 0x7f0b34091a70 "hpx_main" state active
506 <DEB> 0001978640 0x7f0b34091a70 0x7f0b46ffd700 cpu 002 pop-os(0)     SPQUEUE schedule_thread      received HINT_THREAD 000
507 <DEB> 0001978649 0x7f0b34091a70 0x7f0b46ffd700 cpu 002 pop-os(0)     SPQUEUE thread scheduled     HINT_THREAD Thread 000 D 00 Q 000
508 <DEB> 0001978656 0x7f0b34091a70 0x7f0b46ffd700 cpu 002 pop-os(0)     QH_THRD schedule_thread      D 00 Q 000 TM 061 [BP n 000 w 000] [HP n 000 w 000] [NP n 000 w 000] [LP n 000 w 000] T     060 0x7f0b3c087950 0x7f0b3c087950 "hpx_main" queueing thread_priority_normal 
509 <DEB> 0001978669 0x7f0b34091a70 0x7f0b46ffd700 cpu 002 pop-os(0)     _TQ_MC_ schedule_work        stealing 0 D 00 Q 000 n 0000 w 0001 0x7f0b3c087950 0x7f0b3c087950 "hpx_main"
510 reset 0x7f0b46ffd700 0x7f0b34091a70
511 <DEB> 0001978698 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     SCHLOOP state returned       thread 0x7f0b34091a70 0 "hpx_main" state pending n-thread 0 0 "nullptr" n-state pending
512 <DEB> 0001978720 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     SCHLOOP state 5              thread 0x7f0b34091a70 0 "hpx_main" state active
513 <DEB> 0001978732 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     SCHLOOP new state            thread 0x7f0b34091a70 0 "hpx_main" state pending
514 <DEB> 0001978789 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     QH_THRD schedule_thread      D 00 Q 002 TM 059 [BP n 000 w 000] [HP n 000 w 000] [NP n 000 w 000] [LP n 000 w 000] T     058 0x7f0b34091a70 0 "hpx_main" queueing thread_priority_normal
515 <DEB> 0001978806 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     _TQ_MC_ schedule_work        stealing 0 D 00 Q 002 n 0000 w 0001 0x7f0b34091a70 0 "hpx_main" 
516 <DEB> 0001978821 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     _TQ_MC_ get_next_thread      stealing 0 D 00 Q 002 n 0000 w 0000 0x7f0b34091a70 0 "hpx_main"
517 <DEB> 0001978833 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     QH_THRD next_thread_NP       D 00 Q 002 TM 059 [BP n 000 w 000] [HP n 000 w 000] [NP n 000 w 000] [LP n 000 w 000] T     058 0x7f0b34091a70 0 "hpx_main" thread_priority_normal 
518 <DEB> 0001978845 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     QH_NUMA get_next             D 00 Q 002 Qidx 002 taken D 00 Q 002 TM 059 [BP n 000 w 000] [HP n 000 w 000] [NP n 000     w 000] [LP n 000 w 000] T 058 0x7f0b34091a70 0 "hpx_main"
519 <DEB> 0001978867 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     SCHLOOP old state            thread 0x7f0b34091a70 0 "hpx_main" state pending
520 <DEB> 0001978877 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     SCHLOOP state 2              thread 0x7f0b34091a70 0 "hpx_main" state active 
521 <DEB> 0001978886 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     SCHLOOP state 3              thread 0x7f0b34091a70 0 "hpx_main" state active
522 <DEB> 0001978895 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     SCHLOOP state 4              thread 0x7f0b34091a70 0 "hpx_main" state active 
523 <ERR> 0001978905 -------------- 0x7f0b46ffd700 cpu 002 pop-os(0)     TDS     coroutine call       0 thread 0x7f0b34091a70 0 "hpx_main"                             
```

**Comment by biddisco** [comment]
NB. In case you are curious, the debuggin used the `debugging::print` feature, but line 510 is a plain `std::cout` inside the coroutine module, which does not depend on `threading_base` which is why it appears in a different format. (I need threading_base for access to thread_data info, which makes things tricky to see inside the coroutine module).

**Comment by biddisco** [comment]
To finish my explanation. The task is made active and between `state 4` and `state 5` is when it actually runs (scheduling loop), with the returned state shown just before `state 5` - everythig is ok here except the coroutine reset.
Later when the task is again pulled off the queue and rerun - bang line 522, `state 4` is reached and the coroutine call on line 523 when the function is triggered crashes(TDS=thread data stackful). So I can see for sure by tracing back that the problem is when the task returns and the state is set on exit and the coroutine reset called - either correctly, but with `pending` instead of `terminated`, or by mistake.

**Comment by msimberg** [comment]
@biddisco do you know if the RHS `coroutine_.get_thread_id().get()` is `nullptr` or something non-`nullptr` but different from `this` when the assertion fires? I guess some additional print statements could tell you what state the task is supposed to be in (just to distinguish a terminated task that is pending, and vice versa). Are you running the test in DLA-Future or something else?

**Comment by biddisco** [comment]
I'm running DLA future, the coroutine has reset called and the id is `0`. Reset sets it to 0. 
Either the reset is correct but the state remains as pending (instead of terminated) - or the reset is a mistake. 
(I don't know how to tell which state the task should be in because we have to run millions of them before an error occurs - I've temporarily given up on this as I must do other stuff).

**Comment by msimberg** [comment]
I did some testing and the first observation was that 1.4.1 does have this problem as well, but with the default parallel executor, which is similar to the new pool executor on master. After some bisecting the culprit seems to be https://github.com/STEllAR-GROUP/hpx/pull/4090, which fits the errors. What exactly is wrong there I don't know though. Most likely one of the `set_thread_state` functions. @sithhell any guesses?

**Comment by hkaiser** [comment]
> I did some testing and the first observation was that 1.4.1 does have this problem as well, but with the default parallel executor, which is similar to the new pool executor on master. After some bisecting the culprit seems to be #4090, which fits the errors. What exactly is wrong there I don't know though. Most likely one of the `set_thread_state` functions. @sithhell any guesses?

Uhhh, not good... In any case, thanks for isolating this!

**Comment by biddisco** [comment]
https://github.com/STEllAR-GROUP/hpx/pull/4090/files#diff-d643ec2c12b099c89f8c5b2f7d994c65R67-R68
This might be a place to look
