### ISSUE TITLE
hpx_main might not able to start hpx runtime properly

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/hpx#4877]
## Expected Behavior

Runs fine.

## Actual Behavior

Got error:

```
terminate called after throwing an instance of 'hpx::detail::exception_with_info<hpx::exception>'
  what():  Attempting to register a thread outside the HPX runtime and no default pool handler is installed. Did you mean to run this on an HPX thread?: HPX(invalid_status)
Aborted

```

## Steps to Reproduce the Problem

main.cpp:
```
#include <hpx/hpx_main.hpp>
#include <hpx/future.hpp>
#include <hpx/modules/threading.hpp>

int main()
{
  hpx::future<void> f = hpx::async([]() { auto id =  hpx::threads::get_self_id();});

  f.get();
}

```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.13)

find_package(HPX REQUIRED)

add_executable(main main.cpp)
target_link_libraries(main HPX::hpx)

```

## Specifications

... Please describe your environment

  - HPX Version: latest master
  - Platform (compiler, OS):linux, gcc

**Comment by NK-Nikunj** [comment]
@weilewei it is expected behavior. With the current build system if you want to run your HPX application from main, you need to link it to `wrap_main` as well. So you will need to update it to something like:

```
add_executable(main main.cpp)
target_link_libraries(main HPX::wrap_main HPX::hpx)
```

**Comment by weilewei** [comment]
@NK-Nikunj ahh, ok, thanks. Now it works!

**Comment by hkaiser** [comment]
@NK-Nikunj is there a way to detect this problem (at runtime)?

**Comment by NK-Nikunj** [comment]
@hkaiser it will not be possible to have a check at runtime. The variable is set in `hpx_wrap.hpp`, so an exception handler has no way to know if a static library was linked to or not.
Having said that, I do believe that we can get a check at link time. This can be done by calling a random useless function from `hpx_main.hpp` that is present in `libhpx_wrap`. A link time error won't pop up if the static library is linked to. Otherwise, the linker will let the user know that it couldn't a certain function. Don't know if this solution is elegant, but that's the only course of action I can think of.

**Comment by hkaiser** [comment]
@NK-Nikunj the link-time error diagnosis would be fine as well. How much effort would adding that be?

**Comment by NK-Nikunj** [comment]
@hkaiser I looked at the code again. It was possible to add a better error handling at runtime. I've added a PR that should help the user identify when he forgets to link to libhpx_wrap while using hpx_main functionalities.
