### ISSUE TITLE
Clang-format the rest of the files 

### ISSUE THREAD

**Issue by aurianer** [STEllAR-GROUP/hpx#4992]
As the modularization is mainly in place, we could format the rest of the files of the repo (components, examples, tests, etc.) and add this to circleci, that would avoid formatting problems like on #4989

**Comment by hkaiser** [comment]
FWIW, I still would like to continue the modularization for the distributed parts. I think there is still some work to be done.

**Comment by aurianer** [comment]
yep sorry I formulated this wrongly, but should we go ahead with a quick PR formatting everything and then continue modularizing the distributed parts?

**Comment by hkaiser** [comment]
> yep sorry I formulated this wrongly, but should we go ahead with a quick PR formatting everything and then continue modularizing the distributed parts?

I guess it doesn't really make a difference whether we do it now in one big swoop or file by file as before. I'm impartial by now.

**Comment by msimberg** [comment]
I'm mostly indifferent as well, but now might be as good a time as any to do it since there are not many big PRs open at the moment, and most of the changes are in files that are already in modules (algorithms, libcds). It's mostly a question of how many conflicts we end up with and my suspicion is that not many, but I might be forgetting about something. @biddisco, @K-ballo do you have PRs lined up (or open) that you think will be a pain to update if we format everything now? It might be good to at least wait for #4991 to go in first. If we don't do rebases updating PRs will be trivial.

**Comment by K-ballo** [comment]
#4991 should rebase fine after clang-format. I do not have other PRs lined up.

**Comment by aurianer** [comment]
I guess since we are about to switch to clang-format-11 #5421, we could do just after

**Comment by msimberg** [comment]
> I guess since we are about to switch to clang-format-11 #5421, we could do just after

Good idea. There's also not much unmodularized code left. The `examples` and `tests` directories (in the root of the repo) are also unformatted, but those change less frequently, so we might as well do it now.
