### ISSUE TITLE
Bug string_util/split.hpp

### ISSUE THREAD

**Issue by pvthuyet** [STEllAR-GROUP/hpx#5067]
## 1. split a string with `token_compress_mode::off`
call split a string  
```
std::vector<std::string> result;
hpx::string_util::split(result,
	"a-b-",
	[](auto ch) {return ch == '-'; },
	hpx::string_util::token_compress_mode::off);
```
* Expected size of `result`: 2
* Actual size of `result`: 3

## 2. split a string above with `token_compress_mode::on`
Error at ` pred(int(*token_begin))`.  
Cannot dereference string iterator because it is out of range (e.g. an end iterator)
```
while (token_end != std::end(str) && pred(int(*token_begin)))
{
	++token_begin;
}
```
## Specifications
  - HPX Version: master
  - Platform (compiler, OS): Windows

**Comment by msimberg** [comment]
Thanks @pvthuyet for the report!

1. This is expected behaviour. The separator `-` separates three tokens in your input, which I've wrapped in square brackets here: `[a]-[b]-[]`. `split` takes no special action for empty tokens. With `token_compress_mode::on` it may remove empty tokens, but that's because it compresses consecutive *separators*, not because it inherently removes empty tokens. The implementation is based on https://www.boost.org/doc/libs/1_74_0/doc/html/boost/algorithm/split.html and has the same behaviour. Perhaps `token_compress_mode` is somewhat confusingly named...
2. Very nice catch, thank you! This is a plain mistake in the code. I'll fix this.
3. I know we've done a terrible job of communicating this, but you shouldn't rely on this functionality to be stable; it's mainly meant for internal use (it's not listed here https://hpx-docs.stellar-group.org/tags/1.5.1/html/api/public_api.html, although that list is also not complete...). You are of course free to use it as long as you accept that we may change things at any time. In practice this functionality is unlikely to change, but we make no guarantees. If you're looking for something slightly more comprehensive and better supported I recommend you use https://www.boost.org/doc/libs/1_74_0/doc/html/string_algo.html instead.
