### ISSUE TITLE
(Re-)Implement executor API on top of sender/receiver infrastructure

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#5219]
Currently our executor API (customization points) dispatch to an executor interface that was defined by wg21.link/p0443R3. All HPX facilities related to scheduling tasks (algorithms, future, dataflow, async etc.) rely on the executor customization points to perform their operations.

We should reimplement the customization points such that they build upon the sender/receiver infrastructure that has been put in place in HPX based on the latest versions of wg21.link/p0443.

**Comment by msimberg** [comment]
Thanks @hkaiser for putting this up. I think before we even consider this the bulk execution section of P0443 will need some clarity as it's currently underspecified and has quite a few proposals for improvement (and was not implemented in #5053 because of that). Hopefully r15 will specify this a bit better.

**Comment by hkaiser** [comment]
This can be closed as it was implemented in #5429.
