### ISSUE TITLE
HPX should detect the number of cores on the build machine

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/hpx#5661]
## Expected Behavior

HPX should build for the number of cores on the machine you're on by default

## Actual Behavior

It builds for 64 or less cores

**Comment by hkaiser** [comment]
This shouldn't be difficult to achieve if we assume that cmake runs on the node the built libraries should be used on (by default). cmake supports `cmake_host_system_information(RESULT NUM_CPUS_VARIABLE QUERY NUMBER_OF_PHYSICAL_CORES)` to query the number of cores at configuration time.

**Comment by msimberg** [comment]
I still think that we should use dynamic bitsets by default for the CPU masks giving you no limit. They are mainly accessed during scheduler setup, and definitely not in a hot loop in the scheduler. While detecting the number of cores of the host system works in many cases, it won't work on many clusters where login and compute nodes are different.

I've opened https://github.com/STEllAR-GROUP/hpx/pull/5663 to test this hypothesis. If it turns out the dynamic bitsets really do affect performance then detecting the number of cores on the host is still an improvement over the current situation.

**Comment by hkaiser** [comment]
> They are mainly accessed during scheduler setup, and definitely not in a hot loop in the scheduler.

Aren't those accessed during work stealing?

**Comment by msimberg** [comment]
> > They are mainly accessed during scheduler setup, and definitely not in a hot loop in the scheduler.
> 
> Aren't those accessed during work stealing?

No, only to set up the datastructures used in work stealing.

**Comment by hkaiser** [comment]
> > > They are mainly accessed during scheduler setup, and definitely not in a hot loop in the scheduler.
> > 
> > 
> > Aren't those accessed during work stealing?
> 
> No, only to set up the datastructures used in work stealing.

Ok, in that case it doesn't really make sense to optimize the masks for up to 64 cores.

**Comment by msimberg** [comment]
The only "tangible" downside I know of is that the shared priority queue scheduler will be disabled when it's using dynamic bitsets (because it sets up `std::array`s of the maximum core count).

**Comment by hkaiser** [comment]
> The only "tangible" downside I know of is that the shared priority queue scheduler will be disabled when it's using dynamic bitsets (because it sets up `std::array`s of the maximum core count).

Do those have to be static? Replacing them with `std::vector`s might be an option that should incur just some overhead at startup, not during scheduler operation.

**Comment by msimberg** [comment]
There's of course the extra indirection from using vectors but my expectation is that it wouldn't make a difference. @biddisco would know if there is actually any measurable impact of using arrays there instead of vectors. From a purely functional perspective vectors would absolutely be easier than arrays.
