### ISSUE TITLE
Compilers do not match (Fedora 38)

### ISSUE THREAD

**Issue by andreichalapco** [STEllAR-GROUP/hpx#6293]
## Expected Behavior

I've installed hpx via the dnf install on my fedora 38 machine. After this i wanted to compile my first hpx application via the first example in "Quick Start". 

## Actual Behavior

Running 
```bash
cmake -DCMAKE_PREFIX_PATH=/usr/include/hpx ..
```
I received the following error:

CMake Error at /usr/lib64/cmake/HPX/HPX_Message.cmake:51 (message):
  ERROR: Compilers do not match.  In order to compile HPX application it is
  recommended to use the same major version of the compiler as you did for
  HPX.  HPX_CXX_COMPILER=/usr/bin/g++, CMAKE_CXX_COMPILER=/usr/bin/c++.
  HPX_CXX_COMPILER_ID=GNU, CMAKE_CXX_COMPILER_ID=GNU.
  HPX_CXX_MAJOR_VERSION=12, CMAKE_CXX_COMPILER_VERSION=13.  To disable this
  message set HPX_IGNORE_COMPILER_COMPATIBILITY to On.
Call Stack (most recent call first):
  /usr/lib64/cmake/HPX/HPXMacros.cmake:36 (hpx_error)
  /usr/lib64/cmake/HPX/HPXConfig.cmake:164 (hpx_check_compiler_compatibility)
  CMakeLists.txt:3 (find_package)

I think the error is quite clear ... Fedora 38 has the new gcc (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4) which is not the compiler used to compile the package on fedora repo (gcc 12).

## Steps to Reproduce the Problem

Just use Fedora 38 with the latest updates to build a hpx .

## Specifications

  - HPX Version: 1.8.1
  - Platform (compiler, OS): gcc 13.1,1

It would be nice if the repo will be updated with binaries compiled with the latest compiler ... (not everyone wants to install an extra compiler or build hpx from source :)) )

**Comment by hkaiser** [comment]
As you said, the error is quite clear. Either use the same compiler as was used to compile HPX or add `-DHPX_IGNORE_COMPILER_COMPATIBILITY=On` to the cmake command line when configuring your application.

**Comment by vivekd01** [comment]
There is a mismatch between the version of the compiler used to compile the HPX application and the version of the compiler detected by CMake during the configuration process. The recommended approach is to use the same major version of the compiler for both.
Set HPX_IGNORE_COMPILER_COMPATIBILITY to On

**Comment by andreichalapco** [comment]
So using the ignore flag worked ... :) thx. I guess the issue can be closed.

**Comment by vivekd01** [comment]
Respected sir/madam,
I am Vivek Dubey, a computer science postgraduate, I have just entered my
second year of KIIT University. I am new to open source contributions but I
am well aware of  C++ , java. I would  love to contribute to
your organization. Please give me some project to solve the problem.
Regards
Vivek

-- 


* <http://www.kiit.ac.in>*

*
Go Green: Kindly don't print this unless so 
required.*

*
*

*Established U/S 3 of UGC Act and Accredited by NBA of 
AICTE and NAAC of UGC*



Visit us @ *http://www.kiit.ac.in 
<http://www.kiit.ac.in/>*

Follow us @* **|***Twitter 
<https://www.twitter.com/KIITUniversity/>***|***Facebook** 
<https://www.facebook.com/KIITUniversity>*|***Instagram 
<https://www.instagram.com/KIITUniversity/>***|*


 
  
  

The information 
contained in this electronic message and any
  attachments to this message 
are intended for the exclusive use of the
  addressee(s) and may contain 
proprietary, confidential or privileged
  information. If you are not the 
intended recipient, you should not
  disseminate, distribute or copy this 
e-mail. Please notify the sender
  immediately and delete all copies of 
this message and any attachments.
  

 VIRUS WARNING: Computer viruses can 
be
  transmitted via email. The recipient should check this email and any
  
attachments for the presence of viruses. The institute accepts no liability
  for any damage caused by any virus transmitted by this email.

**Comment by hkaiser** [comment]
> Respected sir/madam, I am Vivek Dubey, a computer science postgraduate, I have just entered my second year of KIIT University. I am new to open source contributions but I am well aware of C++ , java. I would love to contribute to your organization. Please give me some project to solve the problem. Regards Vivek

Please use any means of communication as listed [here](https://github.com/STEllAR-GROUP/hpx/blob/master/.github/SUPPORT.md) to get in contact and to discuss details.
