### ISSUE TITLE
Fix Broken Examples

### ISSUE THREAD

**Issue by aserio** [STEllAR-GROUP/hpx#802]
The following examples are either not well enough documented or are broken:
Cancelable_action_client
- [ ] event_synchronization (crashes on more than one thread)
- [x] heartbeat, heartbeat_console (#1597)
- [ ] random_mem_access_client
- [ ] throttle_client

**Comment by sithhell** [comment]
Should we just remove the broken examples from the next release and move fixing it to the next milestone?

**Comment by hkaiser** [comment]
The questions is, which examples  are still broken?

**Comment by parsa** [comment]
If broken means compilation errors then examples "jacobi_omp", "jacobi_nonuniform_om", "pipeline1", "1d_stencil_3_omp", "1d_stencil_4", "transpose", "transpose_smp_block", and "future_reduce" are broken with Intel compilers that use GCC 4.4.7's libstdc++
[Compilation errors Gist](https://gist.github.com/anonymous/d92ac343d87e94f92662)

**Comment by hkaiser** [comment]
> If broken means compilation errors then examples  jacobi_omp ,  jacobi_nonuniform_om ,  pipeline1 ,  1d_stencil_3_omp ,  1d_stencil_4 ,  transpose ,  transpose_smp_block , and  future_reduce  are broken with Intel compilers that use GCC 4.4.7's libstdc++. They run without any issues when built with GCC.

This has been recently fixed

**Comment by satyaki3794** [comment]
I think the nqueens example might also be broken. When I run make examples.nqueen from my build dir and then ./bin/nqueen_client, the program starts correctly (displaying the menu with 4 options : size, default, print and quit). The latter two work as expected but when either of the first two are chosen, the program crashes with the exception <boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<hpx::exception>, and  also, 'this future has no valid shared state'. I have pasted them here: http://pastebin.com/eZ520JQV.

By commenting out specific parts of the code in nqueen_client.cpp, I have found that the issue lies in nqueen::board::init_board(size), present in server/nqueen.hpp. When I ran the code which just took tha input from the user and terminated (commenting out nqueen::board function calls), it ran correctly. The moment I added a call to init_board() but left everything else untouched, the program crashed.
