### ISSUE TITLE
Futures should not require a default constructor

### ISSUE THREAD

**Issue by eschnett** [STEllAR-GROUP/hpx#863]
future.hpp, line 248 says "return Result();". This requires a constructor that takes no arguments, which it shouldn't.

**Comment by krivenko** [comment]
What was the actual resolution of this issue?
Are return types of actions supposed to be default constructible?

Here is an extended version of `tests/unit/actions/return_future.cpp`

https://gist.github.com/krivenko/9e61c80e6adf4cd375af239f723dc752

`test_plain_call_future_non_default_ctor()` fails to compile with the following errors,
```
hpx.git/hpx/util/tuple.hpp:72:24: error: use of deleted function ‘non_default_ctor::non_default_ctor()’
```
```
hpx.git/hpx/lcos/base_lco_with_value.hpp:85:22: error: use of deleted function ‘non_default_ctor::non_default_ctor()’
```

**Comment by K-ballo** [comment]
@krivenko 

> What was the actual resolution of this issue?

This issue was resolved, `Future<R>` no longer requires `R` to be _DefaultConstructible_.

> Are return types of actions supposed to be default constructible?

It's possible, action parameters and return types do have extra requirements, and implicit unwrapping means a remote invocation of an action returning `Future<R>` is treated as if it returned just `R`. I'd suggest creating a dedicated issue with your extended test case, for visibility.

**Comment by hkaiser** [comment]
@krivenko I don't have a quick fix for this - sorry, please give me some time to think it over.
